### ISSUE TITLE
ctl_ohai incorrectly lists an invalid option

### ISSUE THREAD

**Issue by cheeseplus** [chef/chef-web-docs#104]
```
-f FILE_NAME, --file FILE_NAME
The name of an Ohai plugin against which Ohai will run. (Only one Ohai plugin may be specified when using this option.)
```

-f doesn't work and isn't listed by `--help`

**Comment by jamescott** [comment]
Indeed!

(The path was wrong.)

https://github.com/chef/chef-web-docs/commit/26e9e02b6e709a23aeca2eaa26aa59bad1eb24f7

Is rebuilding now. Thanks!
