### ISSUE TITLE
spork does not seem to correctly handle cookbook dependency definitions

### ISSUE THREAD

**Issue by jonknutson** [chef/chef-web-docs#1086]
[spork-dependency-resolution.txt](https://github.com/chef/chef-web-docs/files/1441813/spork-dependency-resolution.txt)
Spork seems to be treating optimistic cookbook dependencies ">=" as pessimistic dependencies "~>". Berkshelf is correctly resolving the dependency.

Steps to recreate:
My cookbook depends pessimistically on the postgresql cookbook:
depends 'postgresql', 	'~> 6.1'
which, in turn, depends optimistically on openssl:
depends 'openssl', '>= 4.0'

Berks has downloaded version 7.1 of the openssl cookbook, optimistically. When I run knife spork omni it fails, because version 7 is not pessimistically greater than 4.0

See attached.

**Comment by brewn** [comment]
Hi @jonknutson, 

I'd suggest directing this to our community, via [Discourse](https://discourse.chef.io/) or via our Slack channel (#chefcommunity). If there's a particular part of the documentation you're following that caused this error, we'd be happy to get it updated.
