### ISSUE TITLE
Misleading info re: recursive directory deletion

### ISSUE THREAD

**Issue by agius** [chef/chef-web-docs#109]
Thanks for the overall excellent core docs! Just wanted to mention a small thing that threw me off today:

In the current docs for `resource_directory` properties, it says the following:

> recursive
>   Ruby Types: TrueClass, FalseClass
> 
>  Create or delete parent directories recursively. For the owner, group, and mode properties, the value of this attribute applies only to the leaf directory. Default value: false.

When using `action :create` , the above applies, and _parent_ directories are created recursively. When using `action :delete` , it deletes _child_ directories and files recursively. This follows POLA - I was expecting `rm -rf` , but the docs made it sound like the entire hierarchy would get blown away.

The example under "Delete Directory" looks correct, but it doesn't elaborate on this:

``` ruby
directory '/tmp/something' do
  recursive true
  action :delete
end
```

From the property text, it looks like this would delete `/tmp` as well as `/tmp/something` and presumably `/tmp/something/a_file.txt` .

Maybe I habitually over-think things, but this threw me off until I tried it out in test-kitchen. A sentence in the attribute text or below the example to clarify the different behavior would be super appreciated. Might help other paranoid over-thinkers and careful-readers 😆 

Cheers,

**Comment by kagarmoe** [comment]
Thanks for the great suggestion!
