### ISSUE TITLE
clarify chef-server.rb file location 

### ISSUE THREAD

**Issue by ericcalabretta** [chef/chef-web-docs#1109]
Knowledge of the chef-server.rb file and its default location is assumed in the documentation. 

New users do not have the necessary information to complete configuration tasks without this formation. For example the ldap configuration guide asks a user to edit the chef-server.rb file without providing a location or further documentation for a new user to find the location. 

"Add the following settings to the chef-server.rb file. These settings must be added to the chef-server.rb file on each machine in the Chef server frontend deployment of a High Availability installation as well as on Chef servers in a standalone installation."
https://docs.chef.io/server_ldap.html#test-ldap-connectivity

The page dedicated to the chef-server.rb file also does not specific a location. 
https://docs.chef.io/config_rb_server.html

I believe the default path is /etc/opscode/chef-server.rb

**Comment by brewn** [comment]
Agreed, the full path needs to be present in at least a few places. Thanks @ericcalabretta
