### ISSUE TITLE
Confusion about FIPS support

### ISSUE THREAD

**Issue by sonic0002** [chef/chef-web-docs#1117]
In the web doc(https://github.com/chef/chef-web-docs/blob/master/chef_master/source/fips.rst), it says we need to have **Chef client 12.19.36** or greater to enable FIPS.

While in another release note and blog, it says that **Chef client 12.8** has FIPS support(https://blog.chef.io/2016/03/16/fips-support-now-generally-available-in-chef-client-12-8/). So which one is correct? It looks like the doc is wrong here.

**Comment by brewn** [comment]
Yep, looks like you're right. Thanks for catching this, I've merged a PR to update the FIPS guide.
