### ISSUE TITLE
Policyfile instructions have wrong method for preferred source

### ISSUE THREAD

**Issue by fletchowns** [chef/chef-web-docs#115]
On this page: https://docs.chef.io/config_rb_policyfile.html

``` ruby
default_source :supermarket
default_source :supermarket, "https://supermarket.example" do |s|
  s.preferred_source_for "chef-client"
end
```

There are several references to a method `preferred_source_for` but that method doesn't exist. The correct method name is `preferred_for`

**Comment by kagarmoe** [comment]
Thanks for your input!
