### ISSUE TITLE
gem_package gem_binary cannot be omitted with Chef client v13

### ISSUE THREAD

**Issue by martinmosegaard** [chef/chef-web-docs#1169]
The documentation for the `gem_package` resource, https://docs.chef.io/resource_gem_package.html , makes it sound like the `gem_binary` property is optional:

```
A property for the gem_package provider that is used to specify a gems binary.
By default, the same version of Ruby that is used by the chef-client will be installed.
```

I have a recipe with a block like this:

```
gem_package 'my_gem' do
  action :install
  source 'my-artifact-repository'
end
```

I can run `kitchen converge` fine with Chef client 12. But with Chef client 13, I get an error like this:

```
Chef::Exceptions::ValidationFailed: Property gem_binary must be one of String!  
You passed false.
```

I have tested with Chef client 13.2.20-1 and 13.4.19-1.

**Comment by brewn** [comment]
@martinmosegaard I've talked to our engineers and they've indicated that this should probably be moved over to https://github.com/chef/chef as what you've demonstrated is not the expected behavior.
