### ISSUE TITLE
Missing documentation for `yum_respository`

### ISSUE THREAD

**Issue by mfischer-zd** [chef/chef-web-docs#117]
The `yum_repository` resource provider is not documented.

**Comment by davidwrede** [comment]
Yup @mfischer-zd, the content and the 12.14 release notes are currently being worked on. They should be out EOD today or early tomorrow.

**Comment by davidwrede** [comment]
@mfischer-zd, we got a little backed up, but these docs are currently building in our pipeline and should be out today.

**Comment by davidwrede** [comment]
@mfischer-zd: Here's a link to the doc: https://docs.chef.io/resource_yum_repository.html.
