### ISSUE TITLE
Add Chef 13.8.3 and 13.8.5 release notes

### ISSUE THREAD

**Issue by tas50** [chef/chef-web-docs#1270]
We've released 2 additional versions of Chef 13.8 that we probably want to mention on the release notes page for chef-client

https://discourse.chef.io/t/chef-13-8-3-released/12703
https://discourse.chef.io/t/chef-client-13-8-5-released/12713

**Comment by brewn** [comment]
https://github.com/chef/chef-web-docs/pull/1273
