### ISSUE TITLE
/organizations/<org>/users API not documented

### ISSUE THREAD

**Issue by coderanger** [chef/chef-web-docs#13]
See https://github.com/chef/chef-server/blob/master/src/oc_erchef/apps/oc_chef_wm/src/oc_chef_wm_org_associations.erl#L8-L15

**Comment by MarkGibbons** [comment]
Has been added at https://docs.chef.io/api_chef_server.html#id79

**Comment by kvivek1115** [comment]
Closed #13 via #2219.
