### ISSUE TITLE
Compliance Profile List is Stale

### ISSUE THREAD

**Issue by larryebaum** [chef/chef-web-docs#1300]
https://docs.chef.io/chef_compliance.html#compliance-profiles

This page lists which compliance profiles Automate ships with out of the box. This list is stale and needs an update... 

The current list is maintained here: https://github.com/chef/compliance-profiles/tree/master/dist/supported

**Comment by IanMadd** [comment]
Currently we don't have any compliance profiles listed in the docs.

It looks like the source is here:
https://github.com/chef/compliance-profiles/tree/main/src

And we could probably find a way to extract each profile name, title, and summary, and dump that content into one yaml file and deploy it with the inspec docs (or wherever).

**Comment by IanMadd** [comment]
This doesn't exist anymore.
