### ISSUE TITLE
Bring back windows_service doc updates for Chef 14

### ISSUE THREAD

**Issue by btm** [chef/chef-web-docs#1312]
A number of Windows service features were added in [chef#6595](https://github.com/chef/chef/pull/6595), reverted in [chef#6763](https://github.com/chef/chef/pull/6763), and added back in [chef#6804](https://github.com/chef/chef/pull/6804). These will be in Chef 14 and haven't been released yet.

Docs were added here in #1194, but then reverted in #1199. Then added back and reverted in #1220, #1244, #1302, and maybe others?

**Comment by brewn** [comment]
These will go back out when Chef 14 goes out. Having them out before Chef 14 was causing some confusion, and goes against our policy of documenting what's in stable anyway. It was my mistake merging them early.

**Comment by jasonwbarnett** [comment]
@btm guessing it's ok to put the docs back since Chef 14 is released now?

**Comment by btm** [comment]
yes. And ideally whatever comes back says chef 14 somewhere, as that wasn't apparent before.

**Comment by brewn** [comment]
https://github.com/chef/chef-web-docs/pull/1331
