### ISSUE TITLE
Update resource docs to better describe name_property

### ISSUE THREAD

**Issue by tas50** [chef/chef-web-docs#1335]
We're describing the name properties in many resources in a very confusing way. We're saying that the default value 'name' when we should be actually describing that the default is the resource's name. Some of the docs get it right. Some have it written in a confusing way.

**Comment by brewn** [comment]
I don't think this is all that confusing, given that `'name'` is what's used in the syntax examples, and when it's given as a default value, the property description typically says something like "The thing to use for x, if it differs from the resource block name." At least that's the case in the Chef 14 resource docs..I'm open to changing it though. @kagarmoe thoughts?
