### ISSUE TITLE
dpkg cannot download deb from URL

### ISSUE THREAD

**Issue by jpmat296** [chef/chef-web-docs#1356]
From install_dk.rst :
> Use your distribution’s package manager to install the Chef Development Kit:
> (...)
> Debian/Ubuntu:
> dpkg -i https://packages.chef.io/files/stable/chefdk/2.4.17/ubuntu/16.04/chefdk_2.4.17-1_amd64.deb

dpkg cannot download deb file with URL. See [here](https://askubuntu.com/questions/51854/is-it-possible-to-install-a-deb-from-a-url) as confirmation.

To be replaced by:
> dpkg -i chefdk_2.4.17-1_amd64.deb

HTH

**Comment by brewn** [comment]
This must have been a copy/paste mistake on my part when I was writing that..thanks!
