### ISSUE TITLE
Editor Extensions

### ISSUE THREAD

**Issue by kagarmoe** [chef/chef-web-docs#1357]
# Editors and Tools
There are packages for Atom that can add syntax highlighting, commands, and code snippets for different languages. The following packages have been developed by the Chef community.
## Atom
* [Chef Language Package](https://atom.io/packages/language-chef)
You write Chef code in a Domain Specific Language (DSL) that is a subset of Ruby. This package identifies files within a cookbook as Chef files. It automatically applies grammar rules for syntax highlighting and code snippet support for defining resources. Once you install the package, you should change an opened file's language to Chef.
* [RSpec Language Package](https://atom.io/packages/language-rspec)
Tests written in ChefSpec use a DSL called RSpec, which is built on top of Ruby. This package provides grammar rules for syntax highlighting and code snippets that help define example groups, examples, and expectations. Once you install the package, you should change an opened file's language to RSpec.
* [InSpec Language Package](https://atom.io/packages/language-inspec)
Tests written in InSpec use Ruby on top of the RSpec DSL. This package provides grammar rules for syntax highlighting and code snippets that help define controls and resource examples. Once you install the package, you should change an opened file's language to InSpec.
* [Habitat Language Package](https://atom.io/packages/language-habitat)
Habitat plans are written with shell scripts. This package provides grammar rules for syntax highlighting and code snippets for callback functions and variable definitions. Once you install the package, you should change an opened file's language to Habitat.
* [Linter](https://atom.io/packages/linter)
This package is a prerequisite for the Foodcritic and Rubocop linters. It installs visual elements that display lint violations as soon as they are discovered.
* [Foodcritic Linter](https://atom.io/packages/linter-foodcritic)
Foodcritic evaluates Chef cookbooks for errors and convention violations. This package provides the linter interface with the issues it discovers. It requires the Linter package.
* [Rubocop Linter](https://atom.io/packages/linter-rubocop)
Rubocop evaluates your Chef cookbooks for errors and convention violations. This package provides the linter interface with the issues it discovers. It requires the Linter package.

**Comment by pschaumburg** [comment]
The Chef Language Package is very old, so I'm currently developing my own one. Including resources, metadata and special things, almost everyone need to use.
Link to it: https://atom.io/packages/language-new-chef

**Comment by tas50** [comment]
We shouldn't point people at Rubocop Linter since we don't want people to use Rubocop on cookbook.

We should use this instead:
https://atom.io/packages/linter-cookstyle
