### ISSUE TITLE
json via http_request

### ISSUE THREAD

**Issue by Ruksov-Andrey** [chef/chef-web-docs#1366]
Is it possible to send a request to the [ELK](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html) via json? 
How to convert json template in syntax **message ({:some => 'data'}.to_json)** ?
Thanks

**Comment by brewn** [comment]
You're probably better off asking this sort of question in the Chef [Community Slack](https://chefcommunity.slack.com) or on the [Chef Mailing List](https://discourse.chef.io).
