### ISSUE TITLE
Changes to rabbitmq settings in Automate optional settings docs

### ISSUE THREAD

**Issue by teknofire** [chef/chef-web-docs#1411]
The docs at https://docs.chef.io/config_rb_delivery_optional_settings.html#rabbitmq are out of date with some changes made 6 months ago.  

This PR https://github.com/chef/automate/commit/de3056317161cb9c0c4d0dc9228519f7bf5fd588 made the following changes:

1. defaults for `rabbitmq['node_ip_address']` has changed from `0.0.0.0` to `127.0.0.1` 
2. a new config option was added for `rabbitmq['management_listen_address']` which defaults to `127.0.0.1`

**Comment by teknofire** [comment]
These config options for rabbitmq are also missing

```
rabbitmq['ssl_certificate'] = '/path/to/rabbitmq.crt'
rabbitmq['ssl_certificate_key'] = '/path/to/rabbitmq.key'
```

**Comment by IanMadd** [comment]
Issue about feature that is EOL as of 2021
