### ISSUE TITLE
Failure to perform join

### ISSUE THREAD

**Issue by davelaramee-ssense** [chef/chef-web-docs#1440]
There is an error at some point that does prevent the recipe from executing properly.
I am no chef savvy, but by doing some test I can guess the following;
I guess it is related with the reboot property and action where there is a mixup?

Recipe:
windows_ad_join 'mydomain.com' do
  domain_name 'mydomain.com'
  domain_user 'mydomain\my.user'
  domain_password 'PASSWORD'
  ou_path 'OU=WMS,OU=Server,DC=mydomain,DC=com'
  action :join
end

Result:
================================================================================
aws_instance.this (chef):     **Error executing action `join`** on resource 'windows_ad_join[corp.ssense.com]'
aws_instance.this (chef):     ================================================================================

aws_instance.this (chef):     Chef::Exceptions::ValidationFailed
aws_instance.this (chef):     ----------------------------------
aws_instance.this (chef):     **Option action must be equal to one of: nothing, request_reboot, reboot_now, cancel!  You passed :immediate.**

aws_instance.this (chef):     Resource Declaration:
aws_instance.this (chef):     ---------------------
aws_instance.this (chef):     suppressed sensitive resource output

aws_instance.this (chef):     Compiled Resource:
aws_instance.this (chef):     ------------------
aws_instance.this (chef):     suppressed sensitive resource output

aws_instance.this (chef):     System Info:
aws_instance.this (chef):     ------------
aws_instance.this (chef):     chef_version=14.1.12
aws_instance.this (chef):     platform=windows
aws_instance.this (chef):     platform_version=6.3.9600
aws_instance.this (chef):     ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]
aws_instance.this (chef):     program_name=C:/opscode/chef/bin/chef-client
aws_instance.this (chef):     executable=C:/opscode/chef/bin/chef-client

**Comment by kagarmoe** [comment]
This is a great question -- perhaps someone on the Chef Community Slack could help you? https://community-slack.chef.io/ 
We have more community resources listed at:
https://docs.chef.io/community.html
Thanks!
