### ISSUE TITLE
knife docs for private supermarket need updated

### ISSUE THREAD

**Issue by jsmartt** [chef/chef-web-docs#145]
The [knife supermarket](https://docs.chef.io/plugin_knife_supermarket.html) docs say in a warning at the top:

> Only use knife supermarket if you are using a Chef 12.12 or earlier. If you are using Chef 12.13 or later, you should use the knife cookbook site commands.

However, the [knife cookbook site](https://docs.chef.io/knife_cookbook_site.html) docs say nothing about connecting to a private supermarket.

Turns out, however, you an actually set the `knife[:supermarket_site]` attribute in your knife.rb file and get your `knife cookbook site` commands to interact with your private supermarket, but I see that documented nowhere besides the [knife supermarket](https://docs.chef.io/plugin_knife_supermarket.html) and [supermarket](https://docs.chef.io/supermarket.html) pages.

So I propose that the [knife cookbook site](https://docs.chef.io/knife_cookbook_site.html) docs need updated to include this config value, or include it in the [knife.rb](https://docs.chef.io/config_rb_knife.html) page. Thoughts?

**Comment by hgregorian** [comment]
👍

**Comment by brewn** [comment]
#1019
