### ISSUE TITLE
Release notes for chef-client 14.2.0 missing

### ISSUE THREAD

**Issue by eheydrick** [chef/chef-web-docs#1468]
The link from the download page goes to https://docs.chef.io/release_notes.html#what-s-new-in-14-2-0 but the most recent release notes are for 14.1.1.

**Comment by Tech356** [comment]
The release notes for `13.9.4`, `13.10.0`, `14.2.0`, and `14.3.37` are also missing.

**Comment by tas50** [comment]
These should be up now.
