### ISSUE TITLE
Custom Resource docs are incorrect 

### ISSUE THREAD

**Issue by coderanger** [chef/chef-web-docs#1469]
Copied from https://github.com/chef/chef/issues/7374

https://docs.chef.io/custom_resources.html#load-current-value shows `load_current_value` inside of an `action` block, which is not a thing, it needs to be at the top level, afaict.

The rest of the examples are correct - just that single one which is incorrect.

**Comment by tas50** [comment]
Fixed by https://github.com/chef/chef-web-docs/pull/1476
