### ISSUE TITLE
Scrub knife.rb mentions

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef-web-docs#1499]
The fact that knife.rb is read by knife, berkshelf and the `chef` command line tool in the chef-dk makes it a poor choice of name.

And we are going to be deprecating the config.json file for berkshelf:  https://github.com/berkshelf/berkshelf/pull/178, which makes it *the* config file for berkshelf.

The `config.rb` name is much better suited to cross-tooling one-config-file-for-all approaches.

There are 337 instances of mentioning knife.rb in the docs and most if not all of those instances should be changed simply with a `s/knife.rb/config.rb/g`.

Any resultant bugs should be fixed, but will be much less impactful that the existing state of the docs, which are stuck on a misleading, old 10-year old convention that has been out of date now for almost 4 years:  https://github.com/chef/chef/commit/b4145b8ea22c91d22fc66fd585e36e1a415ede38#diff-8f2f85d710ce909c6a182a6c33a797ee

**Comment by coderanger** [comment]
So we had previously started down this road a few years ago and then maybe a year or two ago took a hard tack back towards `knife.rb`. I don't personally care which way we go, but we should probably actually stick with it this time :) Also I don't think most users should even know about either file, we should push hard on `credentials` as the standard way to configure stuff IMO with `conknifig.rb` as a fallback for stuff like per-repo settings or complex options.

**Comment by lamont-granquist** [comment]
I don't think we really took a hard tack back to knife.rb, I think nobody bothered to do a proper scrubbing of knife.rb and get work done so the frog just boiled.  I don't recall any actual choice there, it seemed to just be apathy.

I'm okay with credentials since that's forward-looking (and not tool-specific) as well, but knife.rb really needs to end.

**Comment by coderanger** [comment]
There was definitely an explicit discussion to that end but I don't remember in what context, I might be mis-projecting from like a small side chat or something :)

**Comment by lamont-granquist** [comment]
Pretty sure it wasn't in an actual community meeting since otherwise I would have thrown an exception...

**Comment by tas50** [comment]
This has been done!
