### ISSUE TITLE
s/policyfile_zero/chef_zero/g

### ISSUE THREAD

**Issue by cheeseplus** [chef/chef-web-docs#1530]
### User Story
As a user of test-kitchen, I want accurate and up-to-date information regarding Policyfile usage

## Description
`policyfile_zero` has been deprecated as a provisioner for quite some time and `chef_zero` handles this fine.

## Chef Version
n/a

## Platform Version
n/a

### Definition of Done
Replace all `policyfile_zero` with `chef_zero`

### Demo Script / Repro Steps

Example offender: https://docs.chef.io/policyfile.html#test-w-kitchen

**Comment by tas50** [comment]
Looks like this was cleaned up
