### ISSUE TITLE
How to enable task history for windows_task ?

### ISSUE THREAD

**Issue by nitrocode** [chef/chef-web-docs#1589]
### User Story
As a user, I'd like to be able to see when the windows_task were run by enabling history for my tasks. This is more of a question than a feature request because it might exist but not be documented?

## Description
History (disabled) is shown for my task in Task Scheduler.

## Chef Version

```
$ chef --version
Chef Development Kit Version: 3.1.0
chef-client version: 14.2.0
delivery version: master (6862f27aba89109a9630f0b6c6798efec56b4efe)
berks version: 7.0.4
kitchen version: 1.22.0
inspec version: 2.1.72
```

## Platform Version

OSX 10.13.6

### Definition of Done

Ability to enable history on a windows task

### Demo Script / Repro Steps

```
windows_task 'hello' do
  frequency :onstart
  command 'echo Hello'
end
```

**Comment by Vasu1105** [comment]
Hi @nitrocode  I opened the issue https://github.com/chef/chef/issues/7746 because it will be an feature request.

**Comment by IanMadd** [comment]
Closing because this isn't a documentation issue.
