### ISSUE TITLE
HA scenario 1 and 2 wording is wrong

### ISSUE THREAD

**Issue by jblaine** [chef/chef-web-docs#16]
https://github.com/chef/chef-web-docs/blob/master/includes_server_ha/includes_server_ha_drbd_scenario_1and2.rst

> When the acting backup server fails, ...

Trivial, but, in the context of the rendered page at https://docs.chef.io/server_high_availability.html, I don't believe those are the words intended. _Maybe_ "When the active back-end server fails," ?

**Comment by jamescott** [comment]
Very typo. Very fixed.
