### ISSUE TITLE
Document the new credentials system

### ISSUE THREAD

**Issue by tas50** [chef/chef-web-docs#1603]
We need to make sure we document the new credentials system and the knife commands that are used to manage credentials.

**Comment by stuartpreston** [comment]
Adding some references to this as it came up in a recent Community Slack discussion:

1. The original RFC
https://github.com/chef/chef-rfc/blob/master/rfc099-authentication-config-file.md

2. Chef 13.7.16 release notes, Credentials Handling section
https://docs.chef.io/release_notes.html#what-s-new-in-13-7-16

3. Chef 14.4 release notes, Knife configuration profile management commands 
https://docs.chef.io/release_notes.html#whats-new-in-14-4

4. Noah’s demo of how it all works.
https://www.youtube.com/watch?v=z5oFzaWZ7kA

**Comment by mbaitelman** [comment]
As the new target mode is using the credentials file this will be more important in chef 15.
