### ISSUE TITLE
make master fails "chef-web-docs/chef_master/source/debug.rst:28: WARNING: Could not lex literal_block as "ruby". Highlighting skipped."

### ISSUE THREAD

**Issue by MarkGibbons** [chef/chef-web-docs#164]
I followed the README steps to setup and test changes I get the error:

chef-web-docs/chef_master/source/debug.rst:28: WARNING: Could not lex literal_block as "ruby". Highlighting skipped.

for master and for the 12-13 releases when I use the command "make master" or "make 12-13".  Any suggestions for what I might be missing?

thanks,
   Mark

**Comment by colincam** [comment]
Hi Mark,

The most likely problem is your sphinx version. It has to be 1.2.3.  Check it with 
```
  sphinx-build --version
```
It should come back with
```
Sphinx (sphinx-build) 1.2.3
```
You can specify the version on `pip install`. This is now on the chef-web-docs README.md.

**Comment by MarkGibbons** [comment]
Thanks.  That worked.
