### ISSUE TITLE
HA "Machines are stored as Amazon Elastic Block Store (EBS) volumes"

### ISSUE THREAD

**Issue by jblaine** [chef/chef-web-docs#17]
https://github.com/chef/chef-web-docs/blob/master/includes_server_ha/includes_server_ha_aws.rst

> Machines are stored as Amazon Elastic Block Store (EBS) volumes. A passive node monitors the availabilty of the active node, and will take over if required.

Does that say what was meant? I'm not sure. Rendered w/ image above it: https://docs.chef.io/server_high_availability.html

The first sentence confuses me altogether :). I think what it's supposed to say is _something like_, "Backend servers make use of a single Amazon EBS volume." ?

The second sentence could maybe have minor tweaking to be "The passive back-end node monitors the availabilty of the active back-end node, and will take over if required."

**Comment by jamescott** [comment]
Yeah, copypasta typo. Thanks for catching. Is rebuilt.
