### ISSUE TITLE
Typo in chef_master/source/release_notes_chefdk.rst

### ISSUE THREAD

**Issue by callen-IO** [chef/chef-web-docs#1735]
In the "What's New in 3.1" section it currently says:

`knife-tidy 3 is now included with ChefDK. This knife plugin generates reports about stale nodes and helps clean them up.`

It should say `knife-tidy is now` instead of `knife-tidy 3 is now` since the latest version is 1.2.0 and we shouldn't give a fixed version since it will be updated in future releases.

**Comment by tas50** [comment]
Fixed in https://github.com/chef/chef-web-docs/pull/1808
