### ISSUE TITLE
kitchen driver discover no longer available. Doc needs to be updated.

### ISSUE THREAD

**Issue by matteo-bottini** [chef/chef-web-docs#1793]
### User Story
As a <role: Developer, SysAdmin, etc.>, I will use this work when I want to ...

## Description
<! Just trying to use ´kitchen driver discover´ today and it seems it's no longer available.
 https://docs.chef.io/ctl_kitchen.html#kitchen-driver-discover needs to be updated. >

## Chef Version
<! Any >

## Platform Version
<! Any  >

**Comment by tas50** [comment]
Fixed in https://github.com/chef/chef-web-docs/pull/1807

**Comment by tas50** [comment]
Thanks for pointing this out @matteb22
