### ISSUE TITLE
trivial anchor issue in resource_cookbook_file.rst

### ISSUE THREAD

**Issue by bby-bishopclark** [chef/chef-web-docs#1794]
### User Story
Viewing https://docs.chef.io/resource_cookbook_file.html , and perusing the 'source' parameter, it refers to Specificity ; actually, in a few places.  

## Description
About of the of the references to specificity - specifically the ones that connect to the anchor #file-specificity - are broken.  I suspect those are the ones NOT automatically generated, and thus the ones who don't get the same odd anchor name 'id1' .  

## Chef Version
website

## Platform Version
web browser (recent chrome, here)

### Definition of Done
Correct the 'id1' anchor for the File Specificity section back to 'file-specificity', which seems like it's a better anchor and used in many references.

### Demo Script / Repro Steps
1. browse to https://docs.chef.io/resource_cookbook_file.html
2. vgrep for the source parameter, for instance
3. click on the 'file specificity' link therein
4. should take you to the specificity section, currently with the bad anchor tag 'id1'

**Comment by kagarmoe** [comment]
Fixed in migration
