### ISSUE TITLE
knife verbose does not mention -VVV

### ISSUE THREAD

**Issue by scottvidmar** [chef/chef-web-docs#1811]
Our current knife documentation states -VV as providing the most verbose output possible. Currently, that's not the case, and -VVV gives the most verbosity. We need to update that page with -VVV as the most verbosity.

Link: https://docs.chef.io/knife_options.html

**Comment by mjingle** [comment]
Fixed with https://github.com/chef/chef-web-docs/pull/1857. @scottvidmar Thank you for submitting this issue!
