### ISSUE TITLE
chefspec documentation for resource_sudo

### ISSUE THREAD

**Issue by pkleanthous-zz** [chef/chef-web-docs#1825]
### User Story
As a <role: Developer, SysAdmin, etc.>, I will use this work when I want to ...
As a Developer, I would like to write chefspec tests for resource_sudo
## Description
Where can I find the relevant chefspec documentation for resource_sudo?
https://docs.chef.io/resource_sudo.html

**Comment by kagarmoe** [comment]
We automated this a while ago and now the docs are here: https://docs.chef.io/resources/sudo/
