### ISSUE TITLE
Release notes out of date for some time on chef-client (missing 14.11 and 14.12)

### ISSUE THREAD

**Issue by erikng** [chef/chef-web-docs#1880]
Can the release notes be updated for both chef 14.11.21 and now chef 14.12.3 https://docs.chef.io/release_notes.html ?

Some of the release notes are here: https://github.com/chef/chef/blob/master/RELEASE_NOTES.md#chef-client-release-notes-1411

**Comment by mjingle** [comment]
@erikng Thank you for filing this issue! There's an incoming PR that will address this within the week.

**Comment by tas50** [comment]
@erikng I have a local branch that I'll be pushing up this morning with the missing stuff.

**Comment by mjingle** [comment]
Release notes updated via merged PR https://github.com/chef/chef-web-docs/pull/1883. Closing this issue. Thanks again for submitting it, @erikng!
