### ISSUE TITLE
Release notes out of date again for chef 14.12.9

### ISSUE THREAD

**Issue by erikng** [chef/chef-web-docs#1891]
Chef 14.12.9 is out and just like https://github.com/chef/chef-web-docs/issues/1880 there are no release notes to tell us what's changed.

Unfortunately, sifting through the chef changelog doesn't give me much either. We were about to deploy chef 14.12.3 to about 15,000 nodes and would like to understand if chef 14.12.9 is a bug fix release for 14.12.3 before we do this.

Without sounding cranky, it really appears that with this new cadence of stable releases that the chef team hasn't figured out how to maintain release notes. This should be a priority if chef workstation is going to receive bi-weekly/monthly stable releases.

**Comment by erikng** [comment]
Looks like the only way to get the changelog is by viewing the tagged version blob in git, as the CHANGELOG.md file is always overridden by the newest version.

I found the changes in https://github.com/chef/chef/blob/v14.12.9/CHANGELOG.md

Maybe one thing you could do is somehow automatically ingest that particular changelog into the docs?

**Comment by mjingle** [comment]
Release notes for 14.12.9 (https://docs.chef.io/release_notes.html) have been updated. Automation of release notes is an on-going project across all Chef products. Thank you for letting us know about this issue!
