### ISSUE TITLE
Document Ohai config options such as optional plugins

### ISSUE THREAD

**Issue by tas50** [chef/chef-web-docs#1892]
Over the years we've introduced a good number of config options for Ohai. They're buried in the code and at times they made it into the release notes. They don't seem like they ever had it into our docs though so I doubt many users know about them. We should get this stuff into the docs so that more people can use it.

Here's a config example:
https://github.com/chef/ohai/blob/master/RELEASE_NOTES.md#optional-ohai-plugins

**Comment by jaymzh** [comment]
Pretty please add this to the docs. This bites me every time I need to enable an optional plugin.

**Comment by jaymzh** [comment]
Coming back around to this... it bit me again I googled around, couldn't find dogs, eventually resorted to filing a bug for this, then it suggested this bug, which pointed me to the release notes again. *facepalm*

**Comment by tas50** [comment]
optional plugins are all documented now

**Comment by IanMadd** [comment]
These are all documented here: https://docs.chef.io/ohai/#optional-plugins
