### ISSUE TITLE
Turn off DCO in the expeditor config

### ISSUE THREAD

**Issue by tas50** [chef/chef-web-docs#1897]
We don't need to enforce DCO on this repo. We should turn it off.

**Comment by schisamo** [comment]
Don't we need DCO enabled for outside contributions to the docset?

**Comment by tas50** [comment]
Previously we had this repo blacklisted from the DCO bot. It was decided that all contributions were patent free so there was no reason to require DCO

**Comment by schisamo** [comment]
So now that this repos is fully copyrighted (vs creative commons licensed) we might want to reconsider that decision. I'll run that question up the chain.

**Comment by nellshamrell** [comment]
Hey all - this repo is now fully copyrighted and we need to keep the DCO on it. I realize it may be an annoyance, but I believe it will keep things much more straightforward post BMC to require it.

**Comment by schisamo** [comment]
I'm going to close based on feedback from @nellshamrell
