### ISSUE TITLE
chef 12.5 custom resource - action_class documentation

### ISSUE THREAD

**Issue by MarkGibbons** [chef/chef-web-docs#194]
In order to use helper methods in a custom_resource action_class seems to be the way to go.  Action_class is very hard to find in the documentation though.  The best doc I can find about using action_class is contained in this comment "Refer to the [notes about custom resources](https://docs.chef.io/custom_resources_notes.html) if you’re curious about other approaches that use the older styles."  Most people don't look there when they are working on a 12.5 style custom resource because of the "older styles" comment.

I'd like to see something inserted into the custom_resources documentation about action_class.

Thanks,
  Mark

**Comment by tas50** [comment]
This is a definite to-do for improving the custom resources docs. action_class is one of the first things I'd show someone

**Comment by MarkGibbons** [comment]
I can't tell if action class is really needed.  When I did some testing adding a method worked for a resource when defined a couple ways:

**Resource definition**
property ....

action class do
  def a
  end
end

action :dummy do
  a  # worked
end

**So did this, without action class:**

property ....

def a  # single method or mixin
end

action :dummy do
  a  # worked
end

**Comment by tas50** [comment]
If you want access to new_resource in your methods it needs to be in action_class. If you're just showing general purpose logic into methods they don't need action_class.

**Comment by MarkGibbons** [comment]
@tas50 Thank you.  That makes sense.

**Comment by MarkGibbons** [comment]
#258 PR
