### ISSUE TITLE
no actions documented for resource_registry_key

### ISSUE THREAD

**Issue by sarahbakal** [chef/chef-web-docs#1958]
https://github.com/chef/chef-web-docs/pull/1902 removed the actions for resource_registry_key, instead listing properties twice.

**Comment by mjingle** [comment]
@sarahbakal Thank you so much for catching that. We'll put in a fix for that right away.

**Comment by mjingle** [comment]
@sarahbakal Closing this issue since https://github.com/chef/chef-web-docs/pull/1960 with the fix was merged. Thank you again for letting us know!
