### ISSUE TITLE
`converge_by` and the custom resource dsl

### ISSUE THREAD

**Issue by bobchaos** [chef/chef-web-docs#2013]
### User Story
As a cook I want to have clear docs? I guess it's always the same story for this repo o.O

## Description
https://docs.chef.io/dsl_custom_resource.html makes no mention of good old `converge_by` mechanics for idempotency checks, which can leave cooks like me with the wrong impression it's no longer available or desirable.

## Chef Version
12.5 + (since the custom resource DSL)

## Platform Version
N/A

### Definition of Done
A short section, perhaps pulled from old lwrp docs, describing the method and how it can be used for custom idempotency checks that chef internals recognize

**Comment by jordan3825** [comment]
https://docs.chef.io/custom_resources/

On the docs page, `converge_by` is used in one example by never defined or explained.
