### ISSUE TITLE
Document ohai cookbook segment

### ISSUE THREAD

**Issue by gkspranger** [chef/chef-web-docs#2017]
There is a feature related to developing custom Ohai plugins that appears to never have been documented .. See link here :: https://github.com/chef-boneyard/chef-rfc/blob/master/rfc059-ohai-cookbook-segment.md

Long story short, you can create a directory named "ohai" in whatever cookbook you are working on, and drop custom Ohai plugins in there .. They will be sync'ed and re-loaded during the compile phase .. This makes it SO MUCH easier to develop and distribute custom Ohai plugins, which means your cookbook recipes can be more "data driven" -- and therefore hopefully cleaner/easier to maintain ..

Here is my hacky example of using it here :: https://github.com/gkspranger/qik-hit/tree/master/ohai-test

## Chef Version
Chef Infra client, feature available as of 13.x

**Comment by IanMadd** [comment]
This is now documented in https://docs.chef.io/ohai_custom/
