### ISSUE TITLE
404 on documentation link

### ISSUE THREAD

**Issue by isuftin** [chef/chef-web-docs#2033]
At the bottom of https://github.com/chef/chef-web-docs/blob/master/chef_master/source/install_chef_automate.rst there is a link to the chef delivery truck cookbook ( https://github.com/chef/chef-web-docs/blob/master/delivery_truck.html ) which is now a 404

**Comment by IanMadd** [comment]
Hi @isuftin, thanks for submitting the issue. The link `About the delivery-truck Cookbook` is a relative link that works as expected in [https://docs.chef.io/install_chef_automate.html](https://docs.chef.io/install_chef_automate.html).

In addition, this A1 documentation is no longer being updated.
