### ISSUE TITLE
Config option rubygems_url is not documented

### ISSUE THREAD

**Issue by joerg** [chef/chef-web-docs#206]
I just found an option in the chef code [1] about an option "rubygems_url" which if used for installing gems defined in the metadata.rb.
I could not find any documentation about this option but I think its quite handy.

[1] https://github.com/chef/chef/blob/master/lib/chef/cookbook/gem_installer.rb

**Comment by jflemer-ndp** [comment]
@lamont-granquist looks like you added this feature (in chef/chef@1d063284f755b996a6563d7210496afd716a9f2d), and I am in need of using it. Docs would help.

**Comment by iennae** [comment]
https://github.com/chef/chef-web-docs/pull/647

**Comment by iennae** [comment]
This is now documented. Thanks for opening up the issue.
