### ISSUE TITLE
action_class documentation is missing again

### ISSUE THREAD

**Issue by karthanistyr** [chef/chef-web-docs#2066]
### User Story
As a chef cookbook dev, I'd like to have access to comprehensive documentation on Custom Resources DSL.
 
## Description
Since PR #1183, the `action_class` documentation was overwritten with some explainers on `converge_if_changed`, which doesn't seem to make sense (and moreover, the next section is also about `converge_if_changed`). The `action_class` documentation is missing since then.

## Chef Version
N/A, I suspect this documentation impacts all versions as it is the one available on the website.

## Platform Version
N/A

### Definition of Done
There should be an up-to-date documentation on the usage of `action_class` at the address https://docs.chef.io/dsl_custom_resource.html#action-class.

### Demo Script / Repro Steps
Browse to https://docs.chef.io/dsl_custom_resource.html#action-class

![Capture_2019-08-13_19-43-38 443522287](https://user-images.githubusercontent.com/7722196/62953867-90800880-be03-11e9-8664-73771728bea2.png)

**Comment by jflemer-ndp** [comment]
Concur
