### ISSUE TITLE
Use Chef Workstation instead of ChefDK

### ISSUE THREAD

**Issue by kagarmoe** [chef/chef-web-docs#2146]
## User Story
As a new Chef user, I want to use modern tools. I need to install Chef Workstation, not ChefDK.

## Description
Chef Workstation is the preferred tool for Chef Infra, but we continue to recommend ChefDK in the docs.
This is because we don't have a clear directive for resolving differences between the Workstation docs and actual content with those of the DK.

### Definition of Done
[ ] Plan for combination and collation
[ ] Schedule for ChefDK deprecation
[ ] Exchange Chef Workstation for ChefDK in docs
[ ] Update links to point to Chef Workstation package
[ ] Update install/update/remove instructions
[ ] Update Workstation CLI docs
[ ] Update code examples to use Workstation, where relevant

**Comment by tas50** [comment]
This was fixed in #2162
