### ISSUE TITLE
Vagrant instructions don't appear to be working

### ISSUE THREAD

**Issue by davidwrede** [chef/chef-web-docs#215]
Per email feedback:

I was working through the Installing Private Supermarket documentation located at:

https://docs.chef.io/install_supermarket.html

There appears to be some errors when trying to using the documentation as described. It doesn’t appear that the vagrant instructions are working in the ‘Run Supermarket in Kitchen’ section.

**Comment by brewn** [comment]
#998 

Talked with @robbkidd and we agreed that it's best to remove this section.
