### ISSUE TITLE
API docs examples refer to the deprecated and removed Chef::REST

### ISSUE THREAD

**Issue by jtatum** [chef/chef-web-docs#2194]
### User Story
As a Developer, I will read this documentation when I want to integrate with the Chef API via Ruby.

## Description

The current API docs have an examples section, which mentions Chef::REST. Chef/rest was removed in Chef client 13.

https://docs.chef.io/deprecations_chef_rest.html

## Chef Version

Chef Infra 15, or any version > 13.

### Definition of Done
Working Ruby API examples that don't involve usage of Chef::REST.

**Comment by MarkGibbons** [comment]
This issue was fixed.

**Comment by IanMadd** [comment]
Issue resolved with #2387
