### ISSUE TITLE
Remove s390x architecture from supported list for EOL

### ISSUE THREAD

**Issue by jobsolete** [chef/chef-web-docs#2196]
### User Story
As a SysAdmin, I will use this work when I want to know what platforms and architectures are supported for Chef Infra Client.

## Description
We are EOLing `s390x` architecture, so we need to remove it from supported platform/architecture lists [here](https://github.com/chef/chef-web-docs/blob/master/chef_master/source/platforms.rst).

## Chef Version
This is needed for Chef Infra Client `15.5.15` and beyond.

## Platform Version
This applies to Red Hat Enterprise Linux and SUSE Enterprise Linux Server

### Definition of Done
`s390x` is no longer listed under supported platforms in the architecture section.

### Demo Script / Repro Steps
N/A

**Comment by IanMadd** [comment]
Issue resolved with PR #2197
