### ISSUE TITLE
Chef Manage 'group' info wording brain-o

### ISSUE THREAD

**Issue by jblaine** [chef/chef-web-docs#22]
Rendered at https://docs.chef.io/server_orgs.html#default-groups

I believe these:

> The `admins` group is assigned permissions to the following **groups** by default:
> 
> The `billing admins` group is assigned permissions to the following **group** by default:

Should match the wording in these that follow those:

> The `clients` group is assigned the following **permissions** by default to objects on the Chef server:
> 
> The `users` group is assigned the following **permissions** by default to objects on the Chef server:

**Comment by davidwrede** [comment]
Docs have been updated with simplified instructions
