### ISSUE TITLE
chef_repo.html instructs to use a deprecated repository

### ISSUE THREAD

**Issue by MadelineRitchie** [chef/chef-web-docs#23]
chef_repo.html instructs to use the github repo here [https://github.com/chef/chef-repo](https://github.com/chef/chef-repo), however that repo is deprecated.

The repository says you should use chef generate repo instead.

**Comment by jamescott** [comment]
Hi Jason,

Thanks for pointing that out. We're rebuilding with this set of changes:

https://github.com/chef/chef-web-docs/pull/24

james

**Comment by jamescott** [comment]
... and rebuilt. Thanks!
