### ISSUE TITLE
Add a page parameter to the resource yaml config for notes_resource_based_on_package

### ISSUE THREAD

**Issue by tas50** [chef/chef-web-docs#2474]
A good number of resources in Chef Infra are built off the package resource. Right now we have a note that we shove into the resource_description_list that explains the use of the package resource vs. more specific resources. It would make the automation a lot easier if we could make a true/false config value for resources_based_on_package.

current yaml

```yaml
resource_description_list:
- markdown: Use the **zypper_package** resource to install, upgrade, and remove packages
    with Zypper for the SUSE Enterprise and openSUSE platforms.
- note:
    shortcode: notes_resource_based_on_package.md
```

**Comment by IanMadd** [comment]
Solved with #2475
