### ISSUE TITLE
Docs for cron resource needs to be updated for weekday

### ISSUE THREAD

**Issue by Vasu1105** [chef/chef-web-docs#2479]
### User Story
As a <role: Developer, SysAdmin, etc.>, I will use this work when I want to ...

## Description
<! Briefly describe the issue >
Cron resource `weekday` property accepts values in symbols and string as 'sunday', :sunday 
but docs are not updated currently for this.

https://docs.chef.io/resources/cron/

## Chef Version
<! Tell us which version of Chef Infra/Workstation/InSpec you need docs for) >

## Platform Version
<! Tell us which Operating System distribution and version you're running a Chef product on. >

**Comment by tas50** [comment]
Docs have been synced from 16.2 code
