### ISSUE TITLE
Use headers instead of bold so we can use anchors

### ISSUE THREAD

**Issue by mbaitelman** [chef/chef-web-docs#2489]
### User Story
As a community member, I would like that more elements take advantage of Markdown headers instead of using bold tags so I can link to them when helping others out.

## Description
Was helping someone with attributes and wanted to share the docs about `attribute?`. 
As the docs use **bold** for those sections I was not able to link directly the way I could others. 
https://docs.chef.io/attributes/ VS https://docs.chef.io/attributes/#attribute-evaluation-order

## Chef Version
NA
## Platform Version
NA
### Definition of Done
Docs are linkable

### Demo Script / Repro Steps
See Description

**Comment by kagarmoe** [comment]
@chef/docs-team let's explore 2 approaches:
- Using anchors for H4-6
- Refactor pages for MAX H4 header depth

**Comment by IanMadd** [comment]
This is semi fixed. Tim split the attributes page up into multiple pages in #2765. 
`attribute?` is now under https://docs.chef.io/attribute_sources/#attribute-files. We can convert those bolded headings to H3s or H4s.
