### ISSUE TITLE
Fix the warning box on Chef Solo page

### ISSUE THREAD

**Issue by kagarmoe** [chef/chef-web-docs#2501]
https://docs.chef.io/ctl_chef_solo/

<img width="784" alt="Screen Shot 2020-05-21 at 9 43 18 AM" src="https://user-images.githubusercontent.com/4400151/82582982-ae735a00-9b47-11ea-99a2-85772540c9ad.png">

**Comment by IanMadd** [comment]
Fixed with #2502
