### ISSUE TITLE
Supported Versions documentation needs up-to-date deprecation and EOL dates

### ISSUE THREAD

**Issue by jobsolete** [chef/chef-web-docs#2561]
Affected page: https://docs.chef.io/versions/

### Chef Manage

- [ ] Deprecation Date: June 30, 2020
- [ ] End of Life Date: December 31, 2021

### Chef Backend

- [ ] Deprecation Date: June 30, 2020
- [ ] End of Life Date: December 31, 2021

### Push Jobs (Server & Client)

- [ ] Deprecation Date: June 30, 2020
- [ ] End of Life Date: December 31, 2020

### Chef Infra Server 12

- [ ] Deprecation Date: June 30, 2020
- [ ] End of Life Date: December 31, 2020

### Chef Workflow (A2)

- [ ] Deprecation Date: April 1, 2019
- [ ] End of Life Date: December 31, 2020

Additional details can be found in the [New Chef Automate Functionality and End of Life Impacts](https://blog.chef.io/new-chef-automate-functionality-and-end-of-life-impacts/) blog post.

**Comment by IanMadd** [comment]
Closed with #2563
