### ISSUE TITLE
Attribute Hoisting needs to be documented in PolicyFiles

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef-web-docs#2630]
I can only find this reference to hoisting:

https://docs.chef.io/release_notes_client/#policyfile-hoisting

The RFC was here (doesn't have much more info):

https://github.com/chef-boneyard/chef-rfc/blob/e5b5ace33a8cdaacacb364c3751c567e8f1e577f/rfc105-attribute-hoist.md

Implementation was here (again it is pretty simple, but the specs sort of have more examples):

https://github.com/chef/chef/pull/6927

**Comment by IanMadd** [comment]
Content added in #4093
