### ISSUE TITLE
File to import not found or unreadable: foundation-sites/scss/foundation

### ISSUE THREAD

**Issue by mwrock** [chef/chef-web-docs#2647]
After getting the hugo server and deps installed and running, I ran into this error:

```
Error: Error building site: TOCSS: failed to transform "sass/main.scss" (text/x-scss): SCSS processing failed: file "stdin", line 6, col 1: File to import not found or unreadable: foundation-sites/scss/foundation.
```

By copying `themes/docs-new/node_modules/foundation-sites` to `themes/docs-new/assets/scss`, I was able to correct this. Seems like something that should be in the `makefile`. I'd submit a PR but I'm wondering if I am doing something wrong because I'd expect this would be broken for everyone if this was the case.

**Comment by IanMadd** [comment]
I'm not entirely sure why this error was happening, I haven't been able to replicate it. There's a line in the scss file that grabs the content from the foundation scss files (`@import "foundation-sites/scss/foundation";`), I'm not sure why that didn't work. It's possible that running `make clean_all` would correct the problem. Anyway, I'm going to close the issue.
