### ISSUE TITLE
Add Cookstyle docs

### ISSUE THREAD

**Issue by kagarmoe** [chef/chef-web-docs#2658]
### User Story
As a Chef Infra user, I want to understand why my cookbooks fail Cookstyle tests and how to fix the.

## Description
We need to add the Cookstyle docs to the site.

**Comment by IanMadd** [comment]
Here's a start, https://github.com/chef/chef-web-docs/pull/2577
But this should be done with YAML data files.

**Comment by jordan3825** [comment]
The cookstyle comment disable flags are also not documented. 

https://github.com/chef/cookstyle/blob/master/RELEASE_NOTES.md#cookstyle-comments-in-code

It would be nice to have a section about them on them in the cookstyle docs. 

https://docs.chef.io/workstation/cookstyle/

**Comment by tas50** [comment]
@IanMadd We should sit down at some point and figure out a yaml format. I can run with getting that into cookstyle on each commit. I just need to know how you want that formated.

Data that's probably important:

- name
- department
- enabled?
- excluded file paths
- included file paths
- autocorrects?
- target chef version
- version of cookstyle added in
- description string
- example
