### ISSUE TITLE
Chef-solo documentation may cause security issues on implementations

### ISSUE THREAD

**Issue by bennyvasquez** [chef/chef-web-docs#2665]
(submitted on behalf of user [from discourse](https://discourse.chef.io/t/chef-solo-documentation-may-cause-security-issues-on-implementations/17718))

## Description
I'd like to inform you about one potential risk where system administrators might be misled to where the "chef" user is not supposed to have root privileges on the host system.

[chef-solo (executable)](https://docs.chef.io/ctl_chef_solo/#run-as-non-root-user)

Since, non-root users can run Ruby scripts with passwordless sudo privileges defined in the sudoers file then the "chef" user can create a Ruby file containing "system('/bin/bash')" in order to get a root shell.

```
chef@localhost$ sudo chef-solo -c /tmp/shell.rb
root@localhost#
```

Therefore, I think the documentation might need some warning or definition where system administrators need to use chef-solo accessible for unprivileged users who should not become the built-in root user.

Kind regards.

**Comment by damacus** [comment]
Resolved by #2667
