### ISSUE TITLE
Infra client handler docs reference the deprecated chef_handler cookbook

### ISSUE THREAD

**Issue by phiggins** [chef/chef-web-docs#2673]
The docs for infra client handlers references the `chef_handler` cookbook which was deprecated over 2 years ago: https://docs.chef.io/handlers/

See:
* https://supermarket.chef.io/cookbooks/chef_handler
* chef/chef#6642

**Comment by kagarmoe** [comment]
https://github.com/chef/chef-web-docs/issues/2943
https://github.com/chef/chef-web-docs/issues/2123
https://github.com/chef/chef-web-docs/issues/2018
https://github.com/chef/chef-web-docs/issues/74 (!)
