### ISSUE TITLE
checksum in windows_package requires chef 12.6+

### ISSUE THREAD

**Issue by tas50** [chef/chef-web-docs#268]
We should probably call out that this requires 12.6+. I'm not sure if makes sense to do with an info/warning box, but maybe just inline with the description.

**Comment by davidwrede** [comment]
@tas50 For new, deprecated, and removed items, we have those listed on a new line. So in this case, we would have a line below the description with "New in Chef client 12.6." 

At some point, we'll style these in some way, but for right now, we're just focusing on getting as much versioning annotations in as possible. I'll do a quick PR for the checksum property.
