### ISSUE TITLE
Cher Server API for /search/INDEX is missing the INDEX documentation 

### ISSUE THREAD

**Issue by jordan3825** [chef/chef-web-docs#2744]
### User Story
As a Developer, I want to be able to use the documentation when developing my scripts that use the APIs.

## Description

For the `GET /organizations/NAME/search/INDEX` API, the `INDEX` option is not defined.

https://docs.chef.io/api_chef_server/#get-47

## Chef Version
N/A

## Platform Version
N/A

### Definition of Done
The `INDEX` option is documented on the chef server api page.  

### Demo Script / Repro Steps
View https://docs.chef.io/api_chef_server/#get-47

**Comment by phiggins** [comment]
Hi, it looks like the index parameter is described just above where you linked to: https://docs.chef.io/api_chef_server/#get-46
