### ISSUE TITLE
Add a table with versions around the license change 

### ISSUE THREAD

**Issue by Tensibai** [chef/chef-web-docs#2792]
### User Story
As someone helping on slack I'll link that to people asking which version needs licensing

## Description

The actual version page shows GA and EOL products but doesn't show when the switch has been effective, all products having different versionning workflows it makes it hard to remember which version was the latest free (even if unsupported)

### Current Alternative
The actual alternative is scrolling the Releases notes for each product, wich for client is a pain to find back the license change was in 15

### Definition of Done
Give a comprehensive link to peoples on slack wondering which version is under commercial license and which are free
Something alike:

|product|latest free|Licensed since|
|----------|-------------|--------------------|
|chef client|14.?|15.?|
|chef-server|12.19.31|13.0.11|
|inspec|?|3?|
|workstation|0.3.9|?|
|automate|none|always been under license|

I didn't got dig the versions for each, I had the chef-server ones after answering on slack, the others are with questions marks when I'm unsure

I think that's Chef's responsibility to create something crystal clear about what requires a commercial license and what does not according to when it has been pushed in the codebase which is far from user friendly specially on Infra client.

**Comment by IanMadd** [comment]
Hi @Tensibai, thanks for your suggestion, but we're going to close this issue. We always recommend that users run the latest versions of our products. Using older versions could expose users to bugs and security vulnerabilities.
