### ISSUE TITLE
Link to Ohai release notes is broken

### ISSUE THREAD

**Issue by vikramghosh** [chef/chef-web-docs#2799]
The link to the Ohai release notes is broken. I get a 404 when navigating to [https://docs.chef.io/release_notes_ohai/](https://docs.chef.io/release_notes_ohai/)  the broken link is located at [https://docs.chef.io/ohai/]

**Comment by IanMadd** [comment]
Thanks @vikramghosh! 
The Ohai release notes were merged into Client release notes, but we never updated the link. It's good now.
