### ISSUE TITLE
Set `enable_system_nameservers = true`

### ISSUE THREAD

**Issue by kagarmoe** [chef/chef-web-docs#2860]
## Description

Can anyone confirm if the dns resolver example for postgresql is wrong? It shows setting the enable_system_nameservers to false , although if I'm reading things right it looks like it should be true . The elasticsearch example for the same thing uses true. 

https://docs.chef.io/automate/install/#adding-resolvers-for-postgresql-database vs https://docs.chef.io/automate/install/#adding-resolvers-for-elasticsearch

## Chef Version
Automate

**Comment by IanMadd** [comment]
They are now both `true`
