### ISSUE TITLE
Switch to Search.ui

### ISSUE THREAD

**Issue by kagarmoe** [chef/chef-web-docs#2861]
### User Story
As a <role: Developer, SysAdmin, etc.>, I will use this work when I want to ...

## Description
<! Briefly describe the issue >

## Chef Version
<! Tell us which version of Chef Infra/Workstation/InSpec you need docs for) >

## Platform Version
<! Tell us which Operating System distribution and version you're running a Chef product on. >

**Comment by IanMadd** [comment]
Search UI isn't going to work.
