### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by kagarmoe** [chef/chef-web-docs#2877]
SEO team sent a list of broken links that we need to fix.

deeprank|level|indexable|url|found_at_url|found_at_sitemap|failed_reason|http_status_code|links_in_count|rel_links_in_count|sitemaps_in_count|ga_visits|ga_avg_page_load_time|ga_visit_bounce_rate|ga_avg_time_on_page|ga_pageviews_per_visits|backlink_count|backlink_domain_count|links_out_count|external_links_count|internal_links_count|found_in_web_crawl|found_in_sitemap|found_in_google_search_console|found_in_google_analytics|found_in_backlinks|found_in_log_summary|found_in_list|4xx_errors_basic__data_parquet_prod_3345059_59536835_query_id|part|
|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|
0.09|3|false|https://docs.chef.io/inspec/test/integration/verify/controls/aws_nat_gateways.rb|https://docs.chef.io/inspec/resources/aws_nat_gateways/|""|""|404|1|0|0|""|""|""|""|""|""|""|2308|29|2279|true|false|false|false|false|false|false|f5c817b5a00285ff13ff882a2cee71d5|0|
0.09|3|false|https://docs.chef.io/resources/env/|https://docs.chef.io/windows/|""|""|404|1|0|0|""|""|""|""|""|""|""|2308|29|2279|true|false|false|false|false|false|false|f5c817b5a00285ff13ff882a2cee71d5|0|
0.09|3|false|https://docs.chef.io/effortless/effortless_audit/effortless-config.md|https://docs.chef.io/effortless/effortless_audit/|""|""|404|1|0|0|""|""|""|""|""|""|""|2308|29|2279|true|false|false|false|false|false|false|f5c817b5a00285ff13ff882a2cee71d5|0|
0.09|3|false|https://docs.chef.io/release_notes_server/server/config_rb_server_optional_settings/|https://docs.chef.io/release_notes_server/|""|""|404|1|0|0|""|""|""|""|""|""|""|2308|29|2279|true|false|false|false|false|false|false|f5c817b5a00285ff13ff882a2cee71d5|0|
0.09|3|false|https://docs.chef.io/docs/reference/cli/|https://docs.chef.io/azure_cwa_cloud_shell/|""|""|404|1|0|0|""|""|""|""|""|""|""|2308|29|2279|true|false|false|false|false|false|false|f5c817b5a00285ff13ff882a2cee71d5|0|
0.09|3|false|https://docs.chef.io/deprecations_ohai_system_profile/|https://docs.chef.io/chef_deprecations_client/|""|""|404|1|0|0|""|""|""|""|""|""|""|2308|29|2279|true|false|false|false|false|false|false|f5c817b5a00285ff13ff882a2cee71d5|0|
0.09|3|false|https://docs.chef.io/troubleshooting_chef_automate/|https://docs.chef.io/integrate_chef_automate_saml/|""|""|404|1|0|0|""|""|""|""|""|""|""|2308|29|2279|true|false|false|false|false|false|false|f5c817b5a00285ff13ff882a2cee71d5|0|
0.09|3|false|https://docs.chef.io/install_chef_automate/|https://docs.chef.io/delivery_truck/|""|""|404|1|0|0|""|""|""|""|""|""|""|2308|29|2279|true|false|false|false|false|false|false|f5c817b5a00285ff13ff882a2cee71d5|0|
0.09|3|false|https://docs.chef.io/inspec/test/integration/verify/controls/aws_nat_gateway.rb|https://docs.chef.io/inspec/resources/aws_nat_gateway/|""|""|404|1|0|0|""|""|""|""|""|""|""|2308|29|2279|true|false|false|false|false|false|false|f5c817b5a00285ff13ff882a2cee71d5|0|
0.66|3|false|https://docs.chef.io/server_security/|https://docs.chef.io/upgrade_server/|""|""|404|5|0|0|""|""|""|""|""|""|""|2308|29|2279|true|false|false|false|false|false|false|f5c817b5a00285ff13ff882a2cee71d5|0|
0.09|3|false|https://docs.chef.io/inspec/resources/etc_shadow/|https://docs.chef.io/inspec/migration/|""|""|404|1|0|0|""|""|""|""|""|""|""|2308|29|2279|true|false|false|false|false|false|false|f5c817b5a00285ff13ff882a2cee71d5|0|
0.09|3|false|https://docs.chef.io/docs/install/|https://docs.chef.io/automate/servicenow_integration_install/|""|""|404|1|0|0|""|""|""|""|""|""|""|2308|29|2279|true|false|false|false|false|false|false|f5c817b5a00285ff13ff882a2cee71d5|0|
0.09|3|false|https://docs.chef.io/install_chef_automate.html|https://docs.chef.io/automate/delivery_truck/|""|""|404|1|0|0|""|""|""|""|""|""|""|2308|29|2279|true|false|false|false|false|false|false|f5c817b5a00285ff13ff882a2cee71d5|0|
0.27|3|false|https://docs.chef.io/upgrade_client_notes/|https://docs.chef.io/upgrade_client/|""|""|404|2|0|0|""|""|""|""|""|""|""|2308|29|2279|true|false|false|false|false|false|false|f5c817b5a00285ff13ff882a2cee71d5|0|
0.42|3|false|https://docs.chef.io/perform_compliance_scan/|https://docs.chef.io/data_collection/|""|""|404|3|0|0|""|""|""|""|""|""|""|2308|29|2279|true|false|false|false|false|false|false|f5c817b5a00285ff13ff882a2cee71d5|0|
0.09|3|false|https://docs.chef.io/server_replication/|https://docs.chef.io/release_notes_server/|""|""|404|1|0|0|""|""|""|""|""|""|""|2308|29|2279|true|false|false|false|false|false|false|f5c817b5a00285ff13ff882a2cee71d5|0|
0.09|3|false|https://docs.chef.io/server_backup_restore/|https://docs.chef.io/backend_failure_recovery/|""|""|404|1|0|0|""|""|""|""|""|""|""|2308|29|2279|true|false|false|false|false|false|false|f5c817b5a00285ff13ff882a2cee71d5|0|
0.09|3|false|https://docs.chef.io/chef_client/|https://docs.chef.io/chef_client_security/|""|""|404|1|0|0|""|""|""|""|""|""|""|2308|29|2279|true|false|false|false|false|false|false|f5c817b5a00285ff13ff882a2cee71d5|0|

**Comment by IanMadd** [comment]
These three PRs :point_up: should take care of this issue as soon as they're all merged, but I'll run that python link checker again just to double check after the last one gets merged.

**Comment by IanMadd** [comment]
I re-ran the linkchecker script and got the following results 👇, although I know it's returning false positives so not all of these are necessarily correct.

There are a bunch of false positives in docs.chef.io/resources/ and I think I can change the way those links are formed so they don't get returned in the results again.

URL        `/delivery_cli/'
Name       `Delivery CLI'
Parent URL https://docs.chef.io, line 9, col 78013
Real URL   https://docs.chef.io/delivery_cli/
Check time 0.602 seconds
Result     Error: 404 Not Found


URL        `/release_notes_push_jobs/'
Name       `Push Jobs'
Parent URL https://docs.chef.io, line 9, col 171226
Real URL   https://docs.chef.io/release_notes_push_jobs/
Check time 1.224 seconds
Result     Error: 404 Not Found

URL        `/infra_language/overview/'
Name       `Chef Infra Language'
Parent URL https://docs.chef.io, line 9, col 170376
Real URL   https://docs.chef.io/infra_language/overview/
Check time 1.676 seconds
Result     Error: 404 Not Found


URL        `/auth/'
Name       `authenticates'
Parent URL https://docs.chef.io/chef_client_overview/, line 16, col 1299
Real URL   https://docs.chef.io/auth/
Check time 3.531 seconds
Result     Error: 404 Not Found
10 threads active,   193 links queued, 3216 links in 3425 URLs checked, runtime 14 minutes, 1 seconds

URL        `/delivery_server_backup/#s3-backups'
Name       `instructions'
Parent URL https://docs.chef.io/aws_marketplace/, line 155, col 1
Real URL   https://docs.chef.io/delivery_server_backup/#s3-backups
Check time 3.093 seconds
Result     Error: 404 Not Found
10 threads active,   178 links queued, 3231 links in 3428 URLs checked, runtime 14 minutes, 6 seconds

URL        `resources/execute/'
Name       `execute resource'
Parent URL https://docs.chef.io/infra_language/shelling_out/, line 9, col 168004
Real URL   https://docs.chef.io/infra_language/shelling_out/resources/execute/
Check time 3.642 seconds
Result     Error: 404 Not Found

URL        `/images/server/server_components_s3_14.svg'
Name       `image'
Parent URL https://docs.chef.io/server/, line 48, col 29
Real URL   https://docs.chef.io/images/server/server_components_s3_14.svg
Check time 3.348 seconds
Result     Error: 404 Not Found


URL        `/images/server/server_components_postgresql_14.svg'
Name       `image'
Parent URL https://docs.chef.io/server/, line 73, col 29
Real URL   https://docs.chef.io/images/server/server_components_postgresql_14.svg
Check time 1.745 seconds
Result     Error: 404 Not Found


URL        `/inspec/resources/etc_shadow/'
Name       `etc_shadow'
Parent URL https://docs.chef.io/inspec/migration/, line 10, col 9374
Real URL   https://docs.chef.io/inspec/resources/etc_shadow/
Check time 2.830 seconds
Result     Error: 404 Not Found

URL        `../../test/integration/verify/controls/aws_nat_gateway.rb'
Name       `integration tests'
Parent URL https://docs.chef.io/inspec/resources/aws_nat_gateway/, line 38, col 53
Real URL   https://docs.chef.io/inspec/test/integration/verify/controls/aws_nat_gateway.rb
Check time 3.721 seconds
Result     Error: 404 Not Found

URL        `../../test/integration/verify/controls/aws_nat_gateways.rb'
Name       `integration tests'
Parent URL https://docs.chef.io/inspec/resources/aws_nat_gateways/, line 23, col 53
Real URL   https://docs.chef.io/inspec/test/integration/verify/controls/aws_nat_gateways.rb
Check time 3.330 seconds
Result     Error: 404 Not Found


URL        `/install_server_ha/'
Name       `High Availability: Backend\nCluster'
Parent URL https://docs.chef.io/release_notes_server/, line 1226, col 89
Real URL   https://docs.chef.io/install_server_ha/
Check time 2.563 seconds
Result     Error: 404 Not Found


URL        `/upgrade_client_notes/'
Name       `view the notes'
Parent URL https://docs.chef.io/release_notes_client/, line 3678, col 43
Real URL   https://docs.chef.io/upgrade_client_notes/
Check time 0.725 seconds
Result     Error: 404 Not Found

**Comment by kagarmoe** [comment]
Done!
