### ISSUE TITLE
chef_gem examples are outdated

### ISSUE THREAD

**Issue by royaldark** [chef/chef-web-docs#29]
This is a copy of [the issue at the old repo](https://github.com/chef/chef-web-docs-2016/issues/788). The examples are still outdated.

**Comment by jamescott** [comment]
https://github.com/chef/chef-web-docs-2016/issues/788

An update is building...

**Comment by jamescott** [comment]
The first example is updated:

https://docs.chef.io/resource_chef_gem.html#examples

and the `compile_time` property is also updated:

https://docs.chef.io/resource_chef_gem.html#properties

applied back to the 12.1 docs when this change first appeared. Hope this helps!

james
