### ISSUE TITLE
Remove references to chef-apply from the docs

### ISSUE THREAD

**Issue by tas50** [chef/chef-web-docs#2907]
We're trying to remove this feature from Chef Infra. It's of limited value to any customers. Step 1 in that deprecation is making sure no one else finds it and starts their Chef journey off with soon to be removed functionality.

**Comment by jordan3825** [comment]
I use this for testing and to try out new resources fairly often. Is there a planned replacement?

**Comment by damacus** [comment]
@jordan3825 you'll want to use [chef-run](https://docs.chef.io/workstation/chef_run/) which is included as part of Chef Workstation.
