### ISSUE TITLE
Update Photo on Community page

### ISSUE THREAD

**Issue by mjingle** [chef/chef-web-docs#2931]
## Description

Photo displayed on [Chef Community page](https://docs.chef.io/community/) features employees or members no longer active in the Chef community. 

### Definition of Done

Photo should be replaced or removed to maintain currency.

**Comment by IanMadd** [comment]
Hi @mjingle Thanks!
![tenor-172496111](https://user-images.githubusercontent.com/8138169/107446378-2bd66480-6af3-11eb-9dcb-0964394efd5b.gif)

**Comment by bennyvasquez** [comment]
Thanks for this! This isn’t a docs issue, but I’ve taken the request to the internal team and will work on getting it taken care of!
