### ISSUE TITLE
Add new config options to Chef Infra Server 14.0

### ISSUE THREAD

**Issue by kagarmoe** [chef/chef-web-docs#2966]
## Description
14.1 adds a few donfig options, but not enough to justify the work for an entire set of minor-versioned docs.
 We need to add the new configs to the docs. 

The tricky part is making it handle 14 vs 14.x

## Chef Version
Chef Infra Server 14.1

**Comment by IanMadd** [comment]
Closed with the above two PRs and also chef/chef-server#2269
