### ISSUE TITLE
(ChefDK) Policyfile doc redundancy

### ISSUE THREAD

**Issue by eikelab** [chef/chef-web-docs#30]
While the _About Policyfile_ page at https://docs.chef.io/policy.html seems to cover the latest implementation, the _Policyfile.rb_ page at https://docs.chef.io/config_rb_policyfile.html is currently rather incomplete and thus misleading (unfortunately the first result in https://docs.chef.io/search.html?q=Policyfile).

Would be helpful to add a link to the "About Policyfile" doc page at the recently updated https://github.com/chef/chef-dk/blob/master/POLICYFILE_README.md since this is still the main "landing page" (https://www.google.de/search?q=chefdk%20policyfile)

**Comment by jamescott** [comment]
https://docs.chef.io/policyfile.html is the new topic. The config_rb_policyfile.rb is about only the config file, but now has a link to policyfile.html. The policy.html topic is reset to be a proper overview to the various policy options (it's not actually hooked in anywhere, but exists in case folks find it via search); policyfile.html is the one hooked in from the left-side navigation. We're going to deprecate most of the words in the POLICYFILE_README.md file now, and point to the chef-docs page.

You caught is right in the middle of making this change :) Hopefully this is helpful.

james

**Comment by edehde** [comment]
_Danke_ @jamescott this will be helpful indeed for evangelizing the _Chef Policy workflow_ in the future :)
