### ISSUE TITLE
Automate the Chef Habitat Release Notes

### ISSUE THREAD

**Issue by kagarmoe** [chef/chef-web-docs#3047]
### User Story
Make the Habitat release notes easy to make and easy to find.

**Comment by IanMadd** [comment]
We do have release notes in packages.chef.io, but we don't have version numbers on https://omnitruck.chef.io/stable/habitat/versions/all. ~~So the primary obstacle is a CDN with updating version numbers.~~

#3623 gets versions from the GitHub API.

- [x] get release notes added to packages.chef.io (looks like there are pages missing)
- [ ] add publish and announce expeditor scripts to habitat repo
- [x] add habitat release notes page chef-web-docs
