### ISSUE TITLE
Swiftype search results page navigation

### ISSUE THREAD

**Issue by IanMadd** [chef/chef-web-docs#3054]
## General details
Improve search page navigation with custom Swiftype search UI.

Currently the Swiftype Search UI only has links for next page and previous page. Expand this to list page numbers as well as next page and previous page.

## Product
[ ] Chef Automate
[ ] Chef Habitat
[ ] Chef Infra Client
[ ] Chef Infra Server
[ ] Chef InSpec
[ ] Other________________

## Update details

Describe the update that needs to be made. Be as specific as possible:

## Existing resources

GitHub Repository:
Issue link(s):
PR link(s):
AHA! link(s):
Other draft documentation:
Related design, business docs, or other information:

## Review

Name of technical reviewer:

**Comment by kagarmoe** [comment]
- Needs analysis
- Needs broken into multiple cards
- Adds pagination
- May need results curation in Swiftype
