### ISSUE TITLE
[BUG] Use appropriate language

### ISSUE THREAD

**Issue by kagarmoe** [chef/chef-web-docs#3075]
## General details

Confirm these changes in the docs:

- `automatic_attribute_blacklist` -> `blocked_automatic_attributes`
- `default_attribute_blacklist` -> `blocked_default_attributes`
- `normal_attribute_blacklist` -> `blocked_normal_attributes`
- `override_attribute_blacklist` -> `blocked_override_attributes`
- `automatic_attribute_whitelist` -> `allowed_automatic_attributes`
- `default_attribute_whitelist` -> `allowed_default_attributes`
- `normal_attribute_whitelist` -> ``allowed_normal_attributes``
- `override_attribute_whitelist` -> `allowed_override_attributes`
- `enforce_path_sanity` -> `enforce_default_paths`

Also add these to cspell or vale

## Product

[ ] Chef Automate
[ ] Chef Habitat
[ ] Chef Infra Client
[ ] Chef Infra Server
[ ] Chef InSpec
[ ] Other________________

**Comment by tas50** [comment]
https://github.com/chef/chef/blob/6b077d998a0c3168cb7edb19d9d70d122ecafc95/chef-config/lib/chef-config/config.rb#L1005
