### ISSUE TITLE
[INTAKE] Automate AWS & Azure Marketplace

### ISSUE THREAD

**Issue by skkprogress** [chef/chef-web-docs#3101]
## General details

Link to page & section that needs updated: https://docs.chef.io/aws_marketplace/
Business group: Product
Product owner: Sudharshan Kaushik
Team: Lakitu
Date update needs to be published: <tbd>

## Product
- [ ] Chef Automate
- [ ] Chef Habitat
- [ ] Chef Infra Client
- [ ] Chef Infra Server
- [ ] Chef InSpec
- [ ] Chef Workstation
- [ ] Other:________________

## Update details

There has been multiple changes to Chef's Automate listings on AWS marketplace over a period of time. These changes need to be reflected on the docs page correspondingly. 

1. Metered billing listing has been taken down by AWS and is not currently available
2. The BYOL installable is being updated into a single instance cloud formation template

## Existing resources

GitHub Repository:

Other draft documentation: https://progresssoftware.sharepoint.com/:w:/s/ChefCoreC/EeBPyVA7I1NEs_9SON1hub4BiHUO8eYYgvsOuZhsMzy5dw?e=xZ67ri
Related design, business docs, or other information: https://progresssoftware.sharepoint.com/:w:/s/ChefCoreC/EUoD060vSBlEu2Lyux7Q83oB_GJSSsavSFbfrrlaf3NNpQ?e=xmBFyg

## Review

Name of technical reviewer:

**Comment by skkprogress** [comment]
PR - https://github.com/chef/chef-web-docs/pull/3158

**Comment by skkprogress** [comment]
Azure PR - [3187](https://github.com/chef/chef-web-docs/pull/3187) and AWS PR - [3158](https://github.com/chef/chef-web-docs/pull/3158)

**Comment by kagarmoe** [comment]
Looks like we finished this in May
