### ISSUE TITLE
Document Community Supported Chef Server API Libraries

### ISSUE THREAD

**Issue by damacus** [chef/chef-web-docs#3103]
## Description

The [Server Auth Docs ](https://docs.chef.io/server/auth/#chef-infra-server-api-authentication)used to mention third party libraries. It would be helpful to link to the Ruby, Javascript and GoLang libraries for authenticating with the Chef server as these tools handle the hard bit, authenticating with the server. 

- https://github.com/go-chef/chef
- https://www.npmjs.com/package/chef-api

## Possible Solution

Links to the above packages noting they're all third party

## Slack Link

- Question asked by @Tensibai, but I'd also find this quite useful for developing other Chef Server, API clients. 
- [Question asked in Chef Slack](https://chefcommunity.slack.com/archives/C010DJDN4F3/p1619786825035100)

**Comment by IanMadd** [comment]
We don't document third-party tools because there could be problems with those libraries or the developer may stop maintaining/developing them and we don't want to be in the position of documenting something that doesn't work or creates security vulnerabilities.

**Comment by bastien-jove-cbp** [comment]
@IanMadd That's a surprising answer.
Supermarket is made of third party code, the community handler section too: https://docs.chef.io/handlers/#community-handlers

Does it mean the easy access to the community report handlers will disappear too ?
