### ISSUE TITLE
[INTAKE] Instructions for displaying disclosure text and/or ribbon

### ISSUE THREAD

**Issue by SEAjamieD** [chef/chef-web-docs#3116]
To request support for a large documentation project:

1. Fill in the `Documentation project plan` and open an issue
2. Send an email with the rest of information in this template (as much as you have) to docs@pchef.io. 

We will follow up with you soon!

## Documentation project plan

This project plan defines the scope and details for a larger doc project. Complete as much information as you can, as this will help us get better oriented and familiar with the doc needs.

## Product
[x] Chef Automate
[ ] Chef Habitat
[ ] Chef Infra Client
[ ] Chef Infra Server
[ ] Chef InSpec
[ ] Other________________

Brief product description: [3-4 lines]
This feature will allow a customer to display a block of text beneath the login buttons with custom HTML.  It will also allow the customer to display a "Ribbon" across the top of the screen in our login pages (and soon the full Automate UI) with custom text (not HTML), and custom background color and text color.

Product manager: Ankur Mundhra

### Project overview

**Tell us about the project:**

Product name: Automate
Product code name:

Project status page: https://github.com/chef/automate/pull/4978
Business requirements doc:
Design documents: N/A
Functional analysis documents:

### Business group

**Which business does this project fall under:**

Business group: Engineering
Team: Chef Manage (Kallol Roy, Jamie Degnan, Rick Marry)

### Product team

**Who’s who on the project team:**

Product manager: Ankur Mundhra
Project manager: Kallol Roy
Software developers: Kallol Roy, Jamie Degnan
Quality assurance: Kallol Roy, Jamie Degnan
Marketing:
Developer outreach:
Legal:
Field engineer:
Evangelist:
Security:

### Priority

Is this documentation a strategic priority:

Does this project roll up under a strategic leadership goal? If so, which one?

### Target users

**Who is the documentation for:**

[ ] Sysadmins
[x] Developers
[ ] Internal engineers
[ ] Business decision-makers

### Issue tracking

**Where can the tech writer track work related to the project:**

GitHub Repository:
Issue link(s): https://github.com/chef/automate/issues/4974, https://github.com/chef/automate/issues/4934
PR link(s): https://github.com/chef/automate/pull/4978
AHA! link(s): https://chef.aha.io/ideas/ideas/A2-I-92

### Release timelines

Beta partner release date:
General availability (GA) launch date: Unknown
Date docs must be ready to distribute: Unknown

### Information sources

**How does information flow within your team:**

Key team meetings: 8:30am PST Monday through Friday
Team sprints: 
Scrum leader: Kallol Roy
Email lists:
Slack channels: Automate-Team

### Code repositories

**Where the code is stored:**

Repository: https://github.com/chef/automate
Relevant directories and files:

### Testing

**How do we validate the product:**

Test environment:
Test scripts:
Terraform or Vagrantfiles:

In order to test, You'll have to rebuild 3 services at minimum for this to populate correctly. 
The related services are:

1. automate-cli
2. automate-deployment
3. automate-dex - Dex is an OpenID connect provider that we utilize for logging into Automate

In hab studio:
`build components/automate-ui-devproxy`
`build components/automate-cli`
`build components/automate-deployment`
`build components/automate-dex`
`start_all_services`

You'll also need to run `chef-automate config patch dev/patch.toml` in hab studio.  This will connect all the variables we have coming from the config go files.

Next you'll need to get the Automate UI up and running.  To do this, `cd` from the Automate folder into `components/automate-ui` and run `make serve`

If you are already logged into Automate UI, please log out and visit https://a2-dev.test/
If all went well, you should see a block of disclosure text below the login, as well as a blue banner across the top of the screen.

You can then toggle the text of these, or show/hide by opening up the patch.toml file and changing the `show` attributes to false or changing the text.  In order to pick up the new changes you'll need to run `chef-automate config patch dev/patch.toml` again in hab studio.

**How do we report problems:**

### Will this documentation be public or protected:

Protected behind a login: y/n - Unknown, will learn and report back
Public to everyone: y/n

### Documentation size estimate
Medium amount, There are about 5 variables that need to be popluated for this to work.

### Scope of content requests
Instructions no how to setup the config files.

Documentation: y
UX microcopy: n
Screencasts: n
Email campaign content: y/n
Blog articles: y/n
Other: y/n

### Reviewers for content

**Who will provide the technical review for the docs and other content:

Person 1: 
Person 2:

### Support post-launch

**Who will support the product post-launch:**

Support team:
Is the support aware of this project: y/n
Long-term owner post-launch:

### Internal product wiki/resource pages

**What wiki/resource pages are important to be aware of for this project:**

page:
page:
page:

### Marketing support

Do you need Marketing support? y/n
Have you reached out to anyone in Marketing? n
If yes, who is the Marketing contact for this project:

### Other

**List any other details not requested above that might be important to know.**

**Comment by kagarmoe** [comment]
Closed by https://github.com/chef/automate/pull/5273
