### ISSUE TITLE
Add meta description content to desktop resource pages

### ISSUE THREAD

**Issue by kagarmoe** [chef/chef-web-docs#3122]
desktop resource pages also have no meta description content. This one's more complicated.

**Comment by IanMadd** [comment]
My approach to this is to kill two birds with one stone. The Desktop resource pages are generated using a shortcode, however they could be generated with the same layout that's used to create the Infra resource pages. If we do that then the existing meta description tag partial will just work as it currently is and I can delete the shortcodes used to create the desktop resource pages.

**Comment by IanMadd** [comment]
This is resolved with chef/desktop-config#370, #3179, and #3195.
