### ISSUE TITLE
InSpec resource docs

### ISSUE THREAD

**Issue by IanMadd** [chef/chef-web-docs#3135]
## Documentation project plan

This project plan defines the scope and details for a larger doc project. Complete as much information as you can, as this will help us get better oriented and familiar with the doc needs.

## Product
[ ] Chef Automate
[ ] Chef Habitat
[ ] Chef Infra Client
[ ] Chef Infra Server
[X] Chef InSpec
[ ] Other________________

Brief product description: [3-4 lines]

Get the InSpec resource pack docs into chef-web-docs and synced with Expeditor:

- inspec-aws
- inspec-azure
- inspec-gcp
- inspec-habitat

### GCP

The GCP docs are generated from [Magic Modules](https://github.com/modular-magician/inspec-gcp) and we don't have a whole lot of ability to change how they're formatted, so I'll restore the [docs rake task](https://github.com/inspec/inspec/blob/master/tasks/docs.rb) so it can bring in those GCP resource docs and then just update the page frontmatter. And config expeditor to update the GCP docs in the `inspec/inspec` repo when there's a new InSpec release.

### AWS, Azure, Hab

- These aren't formatted the way they should be so I'll write some Python to change the text of these
- Add Hugo config to add them to chef-web-docs
- Delete any matching content from `inspec/inspec` and add the content from the `inspec-<platform>` repos.
- Add expeditor config to `chef-web-docs` to update them whenever there's a PR that's merged that updates the platform docs. 

## Others

There's no docs for aliacloud resources.

**Comment by kagarmoe** [comment]
There's a board just for InSpec now, so I'm closing this out.
