### ISSUE TITLE
chef_group throwing OpenSSL::SSL::SSLError

### ISSUE THREAD

**Issue by pariminaresh** [chef/chef-web-docs#316]
Issue here
- knife commands are working fine
- But chef_group resource throws error.The same working fine with private server but failing with Enterprise server - OpenSSL::SSL::SSLError

Below is the peace of code, Im running:
------->
hash = {:chef_server_url=>"chef.ec.com", :options=>{:client_name=>'admins', :signing_key_filename=>'/tmp/admins.pem',:api_version=>"2"}}

chef_group "Create_group" do
    name "test_group"
    chef_server hash
end
<-------
1.Am I missing anything ssl related in hash?
2.Why it works for private server & why not enterprise server?Extra level of SSL validations?

Your help is greatly appreciated.

Thanks

**Comment by brewn** [comment]
As with your previous opened issue, I'd recommend asking these sort of questions on our [Slack](http://community-slack.chef.io) or [Discourse](http://discourse.chef.io).

Again, apologies for not getting to this sooner.
