### ISSUE TITLE
Expeditor update of Cookstyle cops pages

### ISSUE THREAD

**Issue by IanMadd** [chef/chef-web-docs#3178]
## General details

We use expeditor to update the cookstyle cops YAML files, this works great except when there are new cops added or old cops deleted. In those cases, Expeditor is configured to run [`make cookstyle_cops_pages`](https://github.com/chef/chef-web-docs/blob/master/Makefile#L38) which takes about 4 minutes and exceeds the amount of time that an expeditor script is allowed to run, this makes Expeditor fail and we get no PR.

## Product

[ ] Chef Automate
[ ] Chef Habitat
[ ] Chef Infra Client
[ ] Chef Infra Server
[ ] Chef InSpec
[X] Other Workstation/Cookstyle

## Describe the update that needs to be made. Be as specific as possible:

Switch the Expeditor script to run in Buildkite.

**Comment by IanMadd** [comment]
It's not 100% clear why this is failing, but this PR #3183 isn't the right approach.

Relevant Expeditor events:
https://chefio.slack.com/archives/C0LA3QLMS/p1620669178052600
https://chefio.slack.com/archives/C0LA3QLMS/p1620667165052500

**Comment by kagarmoe** [comment]
What's the status of this issue?
