### ISSUE TITLE
How do I run a batch command using batch resource?

### ISSUE THREAD

**Issue by ghost** [chef/chef-web-docs#319]
``
batch 'ant-run1' do
cwd 'C:\\BigFish'
code <<-EOH
 'ant.bat build'
EOH
notifies :run, 'batch[ant-run2]', :immediately
end
``
I am getting this error even though batch file exists in the specified working directory
STDERR: The system cannot find the path specified.

**Comment by brewn** [comment]
These types of questions are better suited for our Discourse: https://discourse.chef.io/
