### ISSUE TITLE
Automate the promotion of Chef Infra Server docs

### ISSUE THREAD

**Issue by tas50** [chef/chef-web-docs#3247]
**Is your feature request related to a problem? Please describe.**
Chef Infra Server release notes are manually updated which means they're often missed and then customers / CFTs dont' have the latest release notes.

**Describe the solution you'd like**
We already handle release announcements from the wiki similar to Automate/Workstation. It would be great to get a similar release notes setup to those projects where we store the per release docs and then make them available to the docs at the time of releae.

**Describe alternatives you've considered**
I'm up for whatever. As long as it takes the people out of theloop.

**Comment by IanMadd** [comment]
Closed with #3301
