### ISSUE TITLE
Backup and Restore 

### ISSUE THREAD

**Issue by caramcc** [chef/chef-web-docs#325]
Is [`/var/opt/opscode/drbd/data/postgresql_9.2`](https://github.com/chef/chef-web-docs/blame/master/chef_master/source/server_backup_restore.rst#L89) still the correct path for the postgresql data in the chef server? The docs indicate that this is the correct location for postgresql files, but that location doesn't exist on my chef server, and other docs seem to indicate that DRBD is deprecated as of v12.9 (I'm running v12.11.1).

If this location isn't correct, which directory(s) should I be excluding when I'm untarring my backup dump? Would that be `/var/opt/opscode/postgresql/9.2/data`?

**Comment by shatil** [comment]
Interesting comprehension, @caramcc.

I read it as trying to avoid restoring the DRBD-specific PostgreSQL data.

I agree with you that it doesn't make sense to copy the database's files, and also have a database dump. I wonder whether the dump is for consistency purposes? This allows backups while Chef server is online. The downside is inflated backup file sizes.

There is another directory that should be ignored on backup and restore: `/var/opt/opscode/local-mode-cache`
```
$ du -sh /var/opt/opscode/local-mode-cache/*
176K	/var/opt/opscode/local-mode-cache/backup
4.0K	/var/opt/opscode/local-mode-cache/chef-client-running.pid
292M	/var/opt/opscode/local-mode-cache/chef-manage_2.4.1-1_amd64.deb
2.3M	/var/opt/opscode/local-mode-cache/cookbooks
8.0K	/var/opt/opscode/local-mode-cache/remote_file
```

Depending on how you installed `chef-manage`, that folder might contain a 300 megabyte `*.deb` file which is ultimately useless to back up... along with the rest of the "local" cache. If you installed `chef-manage` using `apt-get install chef-manage`, this doesn't happen.

The docs don't mention `/var/opt/opscode/local-mode-cache`, but so far I've been able to back up and restore without it, and it's shaved my backup sizes from 380 megabytes to just 80 (and that's including the PostgreSQL files that aren't ignored!).

@caramcc have you tried backing up and restoring without the actual, populated PostgreSQL folder? I'll do that when I get a chance. This is my backup script:
```sh
sudo --user opscode-pgsql /opt/opscode/embedded/bin/pg_dumpall \
    --clean \
    --file /tmp/postgresql-dump.sql
sudo tar \
    --exclude /var/opt/opscode/local-mode-cache \
    -czf chef-server-backup.tar.gz \
    /etc/opscode \
    /var/opt/opscode \
    /tmp/postgresql-dump.sql
```

**Comment by kagarmoe** [comment]
Chef Infra Server now has specific `chef-server-ctl` commands for these. 
The recent PostgreSQL upgrade docs cover backing up 9.6 and will work for the new version.
Chef Manage is technically deprecated and should EOL this year and we're not actively maintaining that content.

I'm closing this issue because time, hopefully, has healed these wounds.
