### ISSUE TITLE
[BUG] Chef Supermarket FQDN setting

### ISSUE THREAD

**Issue by ineednewpajamas** [chef/chef-web-docs#3251]
## General details

https://github.com/chef/chef-web-docs/blame/master/content/install_supermarket.md#L180

## Product

[ ] Chef Automate
[ ] Chef Habitat
[ ] Chef Infra Client
[ ] Chef Infra Server
[ ] Chef InSpec
[x ] Other_Chef Supermarket_

## Describe the update that needs to be made. Be as specific as possible:

I believe `default['supermarket_omnibus']['fqdn'] = 'supermarket.mycompany.com'` should be `default['supermarket_omnibus']['config']['fqdn'] = 'supermarket.mycompany.com'`

Using what is documented does not work and the version with config is referenced elsewhere on this page when talking about the AWS Public IP.

**Comment by kagarmoe** [comment]
closed by #3551
