### ISSUE TITLE
Chef Automate Install Prerequisites are not clear

### ISSUE THREAD

**Issue by smford22** [chef/chef-web-docs#327]
Our prereqs for installing automate state that a license is 'included when you download' Chef Automate, when in fact the 30 day license is emailed to you after providing your information. We should correct this.

>Chef Automate requires a license from Chef to install. A license key valid for 30 days is included when you download Chef Automate. If you would like to continue using Chef Automate after that period, please contact awesome@chef.io for a permanent key.

https://docs.chef.io/install_chef_automate.html#prerequisites

**Comment by kagarmoe** [comment]
Thank you!
