### ISSUE TITLE
[BUG] broken `Download the Chef Automate CLI` command

### ISSUE THREAD

**Issue by kmf** [chef/chef-web-docs#3332]
## General details

Link to page and section that needs updated:
https://docs.chef.io/desktop/desktop_setup_chef/#install-chef-automate-and-chef-infra-server

## Product

[ x] Chef Automate

## Describe the update that needs to be made. Be as specific as possible:

Install code is wrong.
```
curl https://packages.chef.io/files/current/latest/chef-automate-cli/chef-automate_linux_amd64zip | gunzip - > chef-automate && chmod +x chef-automate

```

Code should be ... missing `.zip`

```
curl https://packages.chef.io/files/current/latest/chef-automate-cli/chef-automate_linux_amd64.zip | gunzip - > chef-automate && chmod +x chef-automate

```

**Comment by IanMadd** [comment]
Fixed with chef/desktop-config#418
Thanks @kmf
