### ISSUE TITLE
https://docs.chef.io/server_orgs/ is not a legacy doc

### ISSUE THREAD

**Issue by tas50** [chef/chef-web-docs#3360]
## General details

Link to page and section that needs updated: https://docs.chef.io/server_orgs/

## Product

[ ] Chef Automate
[ ] Chef Habitat
[ ] Chef Infra Client
[x] Chef Infra Server
[ ] Chef InSpec
[ ] Other________________

## Describe the update that needs to be made. Be as specific as possible:

This is a valid server page and not something related to manage or other legacy products

**Comment by IanMadd** [comment]
Done.
