### ISSUE TITLE
https://docs.chef.io/server_users/ is not a legacy doc

### ISSUE THREAD

**Issue by tas50** [chef/chef-web-docs#3362]
## General details

Link to page and section that needs updated: https://docs.chef.io/server_users/

## Product

[ ] Chef Automate
[ ] Chef Habitat
[ ] Chef Infra Client
[x] Chef Infra Server
[ ] Chef InSpec
[ ] Other________________

## Describe the update that needs to be made. Be as specific as possible:

This is basic configuration for infra server. It's not legacy

**Comment by kagarmoe** [comment]
It is also in server: https://docs.chef.io/server/server_users/

**Comment by tas50** [comment]
Can we delete the duplicate one?
