### ISSUE TITLE
Remove reference to manage from https://docs.chef.io/server/

### ISSUE THREAD

**Issue by tas50** [chef/chef-web-docs#3370]
## General details

Link to page and section that needs updated:

## Product

[ ] Chef Automate
[ ] Chef Habitat
[ ] Chef Infra Client
[X] Chef Infra Server
[ ] Chef InSpec
[ ] Other________________

## Describe the update that needs to be made. Be as specific as possible:

Manage should not be listed as a component on this page at this point in time.

**Comment by IanMadd** [comment]
Closing this because of chef/chef-server#3120
