### ISSUE TITLE
Remove detail of nginx service from server requirements page

### ISSUE THREAD

**Issue by tas50** [chef/chef-web-docs#3373]
## General details

Link to page and section that needs updated:

https://docs.chef.io/chef_system_requirements/

## Product

[ ] Chef Automate
[ ] Chef Habitat
[ ] Chef Infra Client
[x] Chef Infra Server
[ ] Chef InSpec
[ ] Other________________

## Describe the update that needs to be made. Be as specific as possible:

This is an implementation detail of the internal components of the server that is not relevant to the need to have 80/443 open.

"These ports are used by the nginx service"

**Comment by kagarmoe** [comment]
Closes https://github.com/chef/chef-web-docs/issues/3373
