### ISSUE TITLE
Remove browser requirements from chef infra server requirements page

### ISSUE THREAD

**Issue by tas50** [chef/chef-web-docs#3374]
## General details

Link to page and section that needs updated:

https://docs.chef.io/chef_system_requirements/#chef-infra-server-on-premises-or-in-cloud-environment

## Product

[ ] Chef Automate
[ ] Chef Habitat
[ ] Chef Infra Client
[x] Chef Infra Server
[ ] Chef InSpec
[ ] Other________________

## Describe the update that needs to be made. Be as specific as possible:

This is a leftover from manage. There's no web browser requirement for the server itself as it is a backend API server.

Under https://docs.chef.io/chef_system_requirements/#chef-infra-server-on-premises-or-in-cloud-environment

"Browser — Firefox, Google Chrome, Safari, or Internet Explorer (versions 9 or better)"

**Comment by dishanktiwari2501** [comment]
The Changes have been made in the following PR: https://github.com/chef/chef-web-docs/pull/3492
