### ISSUE TITLE
Move all Chef Backend docs to legacy section

### ISSUE THREAD

**Issue by tas50** [chef/chef-web-docs#3375]
**Is your feature request related to a problem? Please describe.**

Our docs have sprinkled bits of chef backend all over the place. We already warn people on these pages that they are EOL, but we need to collect them all into a backend section and shove it in legacy.

This would also include removing things like the backend  system requirements from the various infra pages since no one should be installing this new and it only confuses people who then ask us about backend as a new product install.

**Describe the solution you'd like**
Burn it all.

**Describe alternatives you've considered**

**Additional context**

**Comment by kagarmoe** [comment]
The backend content is interspersed with other content and do not make a neat bundle. We can reconsider in December.
