### ISSUE TITLE
Amazon Linux missing from Infra Server

### ISSUE THREAD

**Issue by tas50** [chef/chef-web-docs#3376]
## General details

Link to page and section that needs updated:

https://docs.chef.io/server/install_server_pre/

## Product

[ ] Chef Automate
[ ] Chef Habitat
[ ] Chef Infra Client
[x] Chef Infra Server
[ ] Chef InSpec
[ ] Other________________

## Describe the update that needs to be made. Be as specific as possible:

Amazon Linux 2 is a supported platform that we test and it needs to be included on this page.

**Comment by dishanktiwari2501** [comment]
@tas50  What is the architecture and the Version for Amazon Linux?

**Comment by tas50** [comment]
Amazon Linux 2 on x86_64

**Comment by kagarmoe** [comment]
Closed by #3498
