### ISSUE TITLE
Remove references to EOL chef-client cookbook

### ISSUE THREAD

**Issue by tas50** [chef/chef-web-docs#3380]
## General details

Link to page and section that needs updated:

https://docs.chef.io/install_bootstrap/ and possibly others

## Product

[ ] Chef Automate
[ ] Chef Habitat
[x] Chef Infra Client
[ ] Chef Infra Server
[ ] Chef InSpec
[ ] Other________________

## Describe the update that needs to be made. Be as specific as possible:

We should not be recommending an EOL cookbook to new users.

**Comment by tas50** [comment]
Fow now I'd just remove the whole "Minimum Recommended Recipe Run-List on a Node" section. It's all useless.

**Comment by kagarmoe** [comment]
Closed by #3499
