### ISSUE TITLE
Rename InSpec DSL to InSpec language throughout

### ISSUE THREAD

**Issue by tas50** [chef/chef-web-docs#3382]
## General details

Link to page and section that needs updated: Multiple pages

## Product

[ ] Chef Automate
[ ] Chef Habitat
[ ] Chef Infra Client
[ ] Chef Infra Server
[x] Chef InSpec
[ ] Other________________

## Describe the update that needs to be made. Be as specific as possible:

We're trying not to use the word DSL anywhere. It's a scary thing that new users do not understand and it means day 1 they need to google a CS term to get started. This should just be InSpec Language similar to what we did renaming Recipe DSL to Infra Language.

**Comment by dishanktiwari2501** [comment]
The changes have been made to the inspec/inspec repo. Related PR: https://github.com/inspec/inspec/pull/5694
