### ISSUE TITLE
Bad link for push jobs server package

### ISSUE THREAD

**Issue by tpetchel** [chef/chef-web-docs#339]
This section:
https://docs.chef.io/install_chef_automate.html#id4

contains this link:
https://downloads.chef.io/push-jobs-server/redhat/

which returns a 404. I don't know what the fix involves, thus the issue :)

Should the link be this?
https://downloads.chef.io/push-jobs-server/stable/1.1.6

**Comment by kagarmoe** [comment]
Done!
