### ISSUE TITLE
Automate automate resource count at https://docs.chef.io/inspec/#resources

### ISSUE THREAD

**Issue by tas50** [chef/chef-web-docs#3392]
**Is your feature request related to a problem? Please describe.**

As new resources are merged this number should get updated. Right now it says 80 when the real number is just shy of 500. It makes the product look bad when we don't talk about its full capabilities. 

https://docs.chef.io/inspec/#resources

**Describe the solution you'd like**
When a new resource is merged this count should be updated. We do this in Cookstyle right now. Same could be done directly on the docs using Expeditor.

**Describe alternatives you've considered**
Some other form of magic

**Additional context**

**Comment by IanMadd** [comment]
I almost guarantee that I can make Hugo count InSpec resources.
