### ISSUE TITLE
Remove references to Serverspec from the InSpec docs site

### ISSUE THREAD

**Issue by tas50** [chef/chef-web-docs#3393]
**Is your feature request related to a problem? Please describe.**

When we first release InSpec it was necessary to explain how it differed from Serverspec and why we didn't just further develop that tool. In 2021 that's not necessary and this document is just more confusing content to read. It should just go away.

**Describe the solution you'd like**
Nuke https://docs.chef.io/inspec/inspec_and_friends/#serverspec

**Comment by dishanktiwari2501** [comment]
@tas50  You mean we have to remove the whole section of **Serverspec** and also it's all the references from the doc?

**Comment by kagarmoe** [comment]
Will return to this when @lokeshk1987 requests.
