### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SteveDelFante** [chef/chef-web-docs#3516]
## General details

Link to page and section that needs updated:

## Product

[ ] Chef Automate
[ ] Chef Habitat
[x] Chef Infra Client
[ ] Chef Infra Server
[ ] Chef InSpec
[ ] Other________________

## Describe the update that needs to be made. Be as specific as possible:

on this page  https://docs.chef.io/config_rb_client/ it says:

The client.rb file specifies how Chef Infra Client is configured on a node and has the following characteristics:

This file is loaded every time the chef-client executable is run.
On Microsoft Windows machines, the default location for this file is C:\chef\client.rb. On all other systems the default location for this file is /etc/chef/client.rb.

I am on Windows 10 and I see no  C:\chef\client.rb

bash.exe"-3.1$ pwd
/c/chef
bash.exe"-3.1$ ls -al
total 8
drwxr-xr-x  3 delfante Administrators    0 Oct 25 14:11 .
drwxr-xr-x 16 delfante Administrators 8192 Oct 25 14:11 ..
drwxr-xr-x  2 delfante Administrators    0 Oct 25 14:12 cache

PS C:\chef> chef -v
Chef Workstation version: 21.10.640
Chef Habitat version: 1.6.351
Test Kitchen version: 3.1.0
Cookstyle version: 7.25.6
Chef Infra Client version: 17.6.18
Chef InSpec version: 4.46.13
Chef CLI version: 5.4.2

**Comment by tas50** [comment]
`client.rb` and this document talk about how Chef Infra Client is configured. You are running Chef Workstation which uses a different directory structure and configuration file.  Chef Workstation creates a `~/.chef` directory for you where you can create a `credentials` or `config.rb` file.

**Comment by SteveDelFante** [comment]
Thank you.

Steve Del Fante — Sr. Instructional Designer
425-231-9916 – ***@***.******@***.***>
Chef Software/ProgressSoftware
[signature_648304751]
