### ISSUE TITLE
Feature Request: Searchable Release Notes

### ISSUE THREAD

**Issue by chef-davin** [chef/chef-web-docs#3519]
**Is your feature request related to a problem? Please describe.**
There is a frustration around not being able to search through release notes with the docs search feature.  Particularly for Chef Infra Client

In the previous format, to find things out about less-documented or undocumented things (target mode, powershell_exec, chef-run, compliance folders in cookbooks, etc...) I could go to the release notes and just search the giant page with the browser's search function, but now I have to try to remember the exact release version when a feature was introduced or improved and I can no longer find those things.

**Describe the solution you'd like**
It would be great if searching for an undocumented feature, I could at least be taken to the release page where that feature was introduced or updated so I could get some context around it.

**Describe alternatives you've considered**
Finding all the underdocumented things and creating Issues/PRs for each of them so they actually make it into the docs.

**Comment by IanMadd** [comment]
I think this Issue can be lumped together with chef/chef-web-docs#3273.

I think the goal is that each product has a single page for release notes, that they're static pages and not loaded with JS which will allow search, and then each individual release has a separate page. So something like:

`https://docs.chef.io/release_notes_<PRODUCT>/` for a single static page,

and

`https://docs.chef.io/release_notes_<PRODUCT>/<VERSION>/` for static pages for each individual release note.

One goal is to maintain a single source for the RN so if they're updated in the S3 bucket, the updates will automatically show up in docs.chef.io. That could involve some kind of bash/Expeditor trickery or [Hugo's getJSON](https://gohugo.io/templates/data-templates/#get-remote-data).

🤔

**Comment by IanMadd** [comment]
Close with #3623
