### ISSUE TITLE
Move Supermarket docs to the Supermarket repo

### ISSUE THREAD

**Issue by tas50** [chef/chef-web-docs#3548]
# Move Supermarket docs to the Supermarket repo

## Product
- [ ] Chef Automate
- [ ] Chef Habitat
- [ ] Chef Infra Client
- [ ] Chef Infra Server
- [ ] Chef InSpec
- [x] Supermarket
- [ ] Other________________

Brief product description:

We need to be able to incorporate documentation changes as part of the acceptance criteria for supermarket changes. The best way to do that is to put the docs right in the repo and have them auto promote when we promote the product.

Product manager:

Tim Smith

## Project overview

This is a public repository. If you would prefer to keep the following information confidential, please email this part of the form us at docs@chef.io.

- [ ] It's all good. I'll use the form
- [ ] That's a big nope. Look for my email.

**Tell us about the project:**

- Product name: Supermarket
- Product code name: N/A

- Project status page: N/A
- Business requirements doc: N/A
- Design documents: N/A
- Functional analysis documents: N/A

### Product team

**Who’s who on the project team:**

- Product manager:
- Project manager:
- Software developers:
- Quality assurance:
- Marketing:
- Legal:
- Security:
- Field engineer:
- Evangelist:

### Priority

Is this documentation a strategic priority:

Does this project roll up under a strategic leadership goal? If so, which one?

### Target users

**Who is the documentation for:**

- [ ] Sysadmins
- [ ] Developers
- [ ] Internal engineers
- [ ] Business decision-makers

### Issue tracking

**Where can the tech writer track work related to the project:**

- GitHub Repository:
- Issue link(s):
- PR link(s):
- AHA! link(s):

### Release timelines

- Beta partner release date:
- General availability (GA) launch date:
- Date docs must be ready to distribute:

### Code repositories

**Where the code is stored:**

- Repository:
- Relevant directories and files:

### Testing

**How do we validate the product:**

- Test environment:
- Test scripts:
- Terraform or Vagrantfiles:

**How do we report problems:**

### Documentation size estimate

**How much documentation do you anticipate for this project:**

**How many sprints do you anticipate for the documentation in this project:**

### Reviewers for content

**Who will provide the technical review for the docs and other content:**

- Person 1:
- Person 2:

### Other

**List any other details not requested above that might be important to know.**

**Comment by kagarmoe** [comment]
Closed by https://github.com/chef/supermarket/pull/2372/
