### ISSUE TITLE
"[INTAKE]" Documentation for PG upgrade and migration​ for Automate

### ISSUE THREAD

**Issue by vivek-yadav** [chef/chef-web-docs#3565]
# Documentation for PG upgrade and migration​ for Automate
This documentation will be needed to help users, to Upgrade to Postgres Version 13 from current Version 9.6.
This documentation should also have details on migration path for existing users.
As well as how to connect new Postgres 13.

## Product
- [x] Chef Automate
- [ ] Chef Habitat
- [ ] Chef Infra Client
- [ ] Chef Infra Server
- [ ] Chef InSpec
- [ ] Other________________

Brief product description: [3-4 lines]
This documentation will be needed to help users, to Upgrade to Postgres Version 13 from current Version 9.6.
This documentation should also have details on migration path for existing users.
As well as how to connect new Postgres 13.

Product manager: Ankur Mundhra

## Project overview
This documentation will be needed to help users, to Upgrade to Postgres Version 13 from current Version 9.6.
This documentation should also have details on migration path for existing users.
As well as how to connect new Postgres 13.

This is a public repository. If you would prefer to keep the following information confidential, please email this part of the form us at docs@chef.io.

- [ ] It's all good. I'll use the form
- [ ] That's a big nope. Look for my email.

**Tell us about the project:**

- Product name: Automate
- Product code name: Automate 2

- Project status page: https://github.com/chef/automate/issues/6003
- Business requirements doc:
- Design documents:
- Functional analysis documents:

### Product team

**Who’s who on the project team:**

- Product manager: Ankur Mundhra
- Project manager: Vivek Yadav
- Software developers: Vivek Shankar, Shaik, Shivangi
- Quality assurance:
- Marketing:
- Legal:
- Security:
- Field engineer:
- Evangelist:

### Priority

Is this documentation a strategic priority:

Does this project roll up under a strategic leadership goal? If so, which one?

### Target users
All Automate customers who are willing to move to Latest PG version.

**Who is the documentation for:**

- [x] Sysadmins
- [x] Developers
- [ ] Internal engineers
- [ ] Business decision-makers

### Issue tracking

**Where can the tech writer track work related to the project:**

- GitHub Repository: https://github.com/chef/automate
- Issue link(s): https://github.com/chef/automate/issues/6003
- PR link(s):
- AHA! link(s):

### Release timelines

- Beta partner release date: 
- General availability (GA) launch date: 3rd Jan, 2022
- Date docs must be ready to distribute: 27th Dec, 2022

### Code repositories

**Where the code is stored:**

- Repository: https://github.com/chef/automate
- Relevant directories and files:

### Testing

**How do we validate the product:**

- Test environment:
- Test scripts:
- Terraform or Vagrantfiles:

**How do we report problems:**

### Documentation size estimate

**How much documentation do you anticipate for this project:**

**How many sprints do you anticipate for the documentation in this project:**

### Reviewers for content

**Who will provide the technical review for the docs and other content:**

- Person 1:
- Person 2:

### Other

**List any other details not requested above that might be important to know.**

**Comment by kagarmoe** [comment]
Done!
