### ISSUE TITLE
Add chef backend to the docs site release notes

### ISSUE THREAD

**Issue by tas50** [chef/chef-web-docs#3614]
**Is your feature request related to a problem? Please describe.**

We have a green pipeline of Chef Backend and we're probably going to be shipping it more often now. We need to get the release notes up on the docs site so we can wire up all the automation to get the release notes/announcements going.

**Describe the solution you'd like**

Same magic we have for all the other products

**Describe alternatives you've considered**

Tim CI continues to do the releases.

**Comment by IanMadd** [comment]
Finished with:
- #3623/#3645
- chef/chef-backend#728
