### ISSUE TITLE
Automate Manage release notes

### ISSUE THREAD

**Issue by tas50** [chef/chef-web-docs#3621]
**Is your feature request related to a problem? Please describe.**

Currently release notes for Chef Manage are not up. Only old ones in a hand crafted doc.

**Describe the solution you'd like**

We should utilize the same automation we're using in other products to push release notes on deploy

**Describe alternatives you've considered**

Whatever you think is best

**Comment by IanMadd** [comment]
- [x] Add manage release notes pages to packages.chef.io
- [x] Add Manage release notes to chef-web-docs
- [x] Add expeditor config to chef/chef-manage to handle publishing and announcing releases

**Comment by IanMadd** [comment]
Closed with the above PRs ☝️
