### ISSUE TITLE
[BUG] Update supported releases and dates for Chef Backend

### ISSUE THREAD

**Issue by tas50** [chef/chef-web-docs#3690]
## General details

Link to page and section that needs to be updated:

https://docs.chef.io/versions/#supported-commercial-distributions

## Product

[ ] Chef Automate
[ ] Chef Habitat
[ ] Chef Infra Client
[ ] Chef Infra Server
[ ] Chef InSpec
[x] Chef Backend

## Describe the update that needs to be made. Be as specific as possible:

Chef Backend needs to be moved from "Supported Commercial Distributions" to "Deprecated Products and Versions" and the EOL date set to "December 31, 2022"

**Comment by IanMadd** [comment]
Support/Depraceted/EOL dates are currently under discussion. I'm closing this for now as this might be extended or the date is changing.
