### ISSUE TITLE
[BUG] syntax broken in group resource examples section

### ISSUE THREAD

**Issue by txt-file** [chef/chef-web-docs#3701]
## General details

* https://github.com/chef/chef-web-docs/blob/b536d3605939726c1fcd8632083686ddb2398e7f/data/infra/resources/group.yaml#L100
* https://docs.chef.io/resources/group/#examples

## Product

[ ] Chef Automate
[ ] Chef Habitat
[X] Chef Infra Client
[ ] Chef Infra Server
[ ] Chef InSpec
[ ] Other________________

## Describe the update that needs to be made. Be as specific as possible:

fix broken syntax

**Comment by tas50** [comment]
Fixed by https://github.com/chef/chef-web-docs/pull/3702

**Comment by txt-file** [comment]
That was fast. Especially for a Sunday. Did not expect anything before Monday.

Much appreciated @tas50

**Comment by IanMadd** [comment]
Closed with #3702
