### ISSUE TITLE
[BUG] Docs still refer to delivery mode 

### ISSUE THREAD

**Issue by damacus** [chef/chef-web-docs#3704]
## General details

Link to page & section that needs updated:
Business group: (ex. product, engineering, marketing)
Product owner: @vkarve-chef 
Team: Chef Workstation
Date update needs to be published: ASAP. This is a back fill to an existing deprecation/removal. 

## Product
- [ ] Chef Automate
- [ ] Chef Habitat
- [ ] Chef Infra Client
- [ ] Chef Infra Server
- [ ] Chef InSpec
- [x] Chef Workstation
- [ ] Other:________________

## Update details

Remove reference to the `.delivery` folder, and the delivery-cli everywhere in the docs. 
Optionally replace references to delivery-cli to a note that it has been deprecated. 

## Existing resources

GitHub Repository: 
- https://github.com/chef/chef-cli/pull/201
- https://github.com/chef/chef-workstation/pull/2536
- https://github.com/chef/chef-workstation/pull/2469
- https://github.com/chef/chef_deprecations/pull/8/files

## Review

Name of technical reviewer:

- @damacus

**Comment by vkarve-chef** [comment]
we have https://github.com/chef/chef-workstation/issues/2540 in backlog, will take it up at earliest.

**Comment by IanMadd** [comment]
Closed with #3706 and chef/chef-workstation#2588
