### ISSUE TITLE
bootstrap templates have wrong examples

### ISSUE THREAD

**Issue by spuder** [chef/chef-web-docs#390]
The documentation for bootstrap templates give an example for ubuntu 14.04

Yet all the examples reference ubuntu 12.04

![screenshot 2017-01-10 09 59 10](https://cloud.githubusercontent.com/assets/242382/21815927/8e302ba4-d71b-11e6-8610-dfe73b41ca58.png)

https://docs.chef.io/knife_bootstrap.html

**Comment by kagarmoe** [comment]
![gif-keyboard-6991294219890132549](https://cloud.githubusercontent.com/assets/4400151/22994462/d8fe54a4-f37b-11e6-8aae-118824a345b4.gif)
