### ISSUE TITLE
Documentation update for mount resource for device property

### ISSUE THREAD

**Issue by justme3** [chef/chef-web-docs#399]
The mount resource documentation indicates that the device property is only needed for actions umount and remount.

The behavior, and source code examination, shows that the device property is used much more extensively.  https://github.com/chef/chef/blob/master/lib/chef/provider/mount.rb

**Comment by juliandunn** [comment]
That's the superclass you're looking at, but the subclasses don't necessarily use that property. For example there is no "device" if you were to mount `procfs`.
