### ISSUE TITLE
Link to https://omnitruck.chef.io/products resolves as 403 forbidden

### ISSUE THREAD

**Issue by davidwrede** [chef/chef-web-docs#423]
https://docs.chef.io/api_omnitruck.html has a link to https://omnitruck.chef.io/products which comes up as forbidden for some users. Need to investigate and update link.

**Comment by kagarmoe** [comment]
The link exists on:
https://docs.chef.io/api_omnitruck.html
https://docs.chef.io/install_omnibus.html
https://docs.chef.io/packages.html

**Comment by davidwrede** [comment]
Opened https://github.com/chef/omnitruck/issues/229 to help track down a resolution to the problem.
