### ISSUE TITLE
Subversion resource

### ISSUE THREAD

**Issue by onknows** [chef/chef-web-docs#428]
The subversion resource does not work and has not worked for a long time. Doubt that it will ever be fixed. 

Can we update documentation to reflect this at least? Put a big red warning sign on it warning people to use it/try to use it.

This resource does only one thing well and that is to produce error parse svn info data.

To do something with this resource you first need to create the working copy manually. Which is the primary purpose of the resource. So it is an absolute waste of time to try to do something useful with this resource.

**Comment by kagarmoe** [comment]
Thank you for your continuing involvement in the Chef community.  There is now a warning on the subversion page with links for further information.
