### ISSUE TITLE
[BUG] Missing page for Profile

### ISSUE THREAD

**Issue by jtquach1** [chef/chef-web-docs#4286]
## General details

Link to page and section that needs updated:
https://docs.chef.io/inspec/#how-does-chef-inspec-work

## Product

- [ ] Chef Automate
- [ ] Chef Habitat
- [ ] Chef Infra Client
- [ ] Chef Infra Server
- [x] Chef InSpec
- [ ] Other________________

## Describe the update that needs to be made. Be as specific as possible:
The hyperlink in the sentence "An [InSpec profile](https://docs.chef.io/inspec/profile/) organizes multiple controls into a reusable artifact." has a broken link, https://docs.chef.io/inspec/profile/. The resulting page is a 404 Not Found. The new link could probably be https://docs.chef.io/inspec/profiles/.

**Comment by IanMadd** [comment]
Fixed with inspec/inspec#7040
