### ISSUE TITLE
links to old documentation [docs.opscode.com] don't redirect to new domain [docs.chef.io]

### ISSUE THREAD

**Issue by maraaaa** [chef/chef-web-docs#444]
Hello,

`http://opscode.com` redirects to `http://chef.io`.  However, it seems, that `http://docs.opscode.com` does not redirect to `http://docs.chef.io`

For example, I was googling for a [git resource [1]](http://i.imgur.com/wzEaCWF.png), the first link is a direct to the resource I need, but being human the "Check out a Git repository with chef?" being literally my question, was what naturally got my attention first.  (Yea, I could read documentation, or I could see someone who's solved the problem and maybe adapt their solution... c'mon, I'm lazy.)  The [accepted answer [2]](http://stackoverflow.com/a/11779825) has a comment to the documentation, but it's from the opscode days.

That I hit this specific link was pure happenstance, and I'm certainly not suggesting that you should curate the internet for dead links... lol.  However, it does seem that a simple `s/opscode.com/chef.io/ =~ 'http://docs.opscode.com/resource_git.htm'` [[3]](http://docs.opscode.com/resource_git.htm)[[4]](https://docs.chef.io/resource_git.htm) solves the 404 so I suspect a 301 from "docs.opscode.com" => "docs.chef.io" would redirect a lot of old links across the internet to the correct location and even if "docs.chef.io/foo" doesn't exist, I think it's better than the default 404 page [[5]](http://docs.opscode.com/thisreallydoesntexist.html) vs [[6]](https://docs.chef.io/thisreallydoesntexist.html)

Even redirecting "http://docs.opscode.com$request" to "http://docs.chef.io" I think would be beneficial, since you'd at least get the docs page instead of the generic nginx 404. 

Anyway, that's just my thought.

Thanks!
- @maraaaa

Links: 
[1] http://i.imgur.com/wzEaCWF.png
[2] http://stackoverflow.com/a/11779825
[3] http://docs.opscode.com/resource_git.htm
[4] https://docs.chef.io/resource_git.htm
[5] http://docs.opscode.com/thisreallydoesntexist.html
[6] https://docs.chef.io/thisreallydoesntexist.html

**Comment by kagarmoe** [comment]
Thank you for your suggestions.  Stackoverflow is a great resource and fortunately older links are updated in the comments. While we are currently unable to use wildcard redirects in the manner that you have suggested, we will take your recommendation and redirect "http://docs.opscode.com" to "http://docs.chef.io".
