### ISSUE TITLE
12.7 What's New has old docs in it 

### ISSUE THREAD

**Issue by natewalck** [chef/chef-web-docs#5]
Wasn't sure if this was the right place, but the release notes here:

https://docs.chef.io/release/12-7/release_notes.html

have a defect from a previous change (...s (.profile files) on the Mac OS X platform.). it should be (.mobileconfig) files.

Let me know if you need other info.

Thanks!

Nate

**Comment by jamescott** [comment]
Ah, I see. Good catch. I still need to get one more new resource into the release notes. This change is in the rebuild pipeline.

james

**Comment by jamescott** [comment]
Closing this out, as that list item at the top of the file is updated. My next task is to get the 12.7 docs properly released, which will move this to the main release notes and add the osx_profile resource to the main collection.
