### ISSUE TITLE
(suggestion) Add link to rfc21 to supported platforms to system requirements

### ISSUE THREAD

**Issue by vinyar** [chef/chef-web-docs#51]
Link to be added (or duplicated):
https://github.com/chef/chef-rfc/blob/master/rfc021-platform-support-policy.md

Page in question:
https://docs.chef.io/chef_system_requirements.html

Reason:
that RFC is the best authoritative source of supported platforms, however it's not referenced anywhere in our official docs, which leads customers to infer supported platforms from the download page, or other non-authoritative sources.

**Comment by kagarmoe** [comment]
Thanks for the great idea!  We've made it so the https://docs.chef.io/chef_system_requirements.html has a link to the https://docs.chef.io/platforms.html page, which is a list of supported platforms including recent additions such as Ubuntu 16.04 and Windows 10.
