### ISSUE TITLE
Update Chef Client 12.7 release notes

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef/chef-web-docs#52]
It looks like some things were left out when compared to what's in the chef repo. One of the significant potentially breaking changes is "Chef::REST is no longer globally required, so if your code uses Chef::REST, you must ensure that you require it correctly".

It would be nice to have that and others copied into the docs.chef.io Chef Client 12.7 release notes.

https://github.com/chef/chef/blob/12.7.2/RELEASE_NOTES.md#chefrest

**Comment by jamescott** [comment]
This is now updated. Thanks @jeremiahsnapp.
