### ISSUE TITLE
Document how to install Supermarket in air-gapped environment

### ISSUE THREAD

**Issue by davidwrede** [chef/chef-web-docs#549]
Looks like https://github.com/chef/supermarket/issues/1512 needs to be addressed from the product side as well.

**Comment by davidwrede** [comment]
Looks like https://github.com/chef/supermarket/issues/1512 needs to be addressed from the product side as well.

**Comment by vinyar** [comment]
I started writing this up a while back, you're welcome to pillage:
http://releaseengineer.blogspot.com/2016/10/setting-up-chef-automate-delivery-in.html

**Comment by brewn** [comment]
s/supermarket/everything

**Comment by brewn** [comment]
https://docs.chef.io/install_chef_air_gap.html
