### ISSUE TITLE
include_attribute seems to be missing from the docs

### ISSUE THREAD

**Issue by vinyar** [chef/chef-web-docs#563]
the only place I was able to find any reference to `include_attribute` is here:
https://github.com/chef-boneyard/chef-web-docs-2016/blob/dc540f7bbc2d3eedb05a74f34b1caf25f1a5d7d3/includes_cookbooks/includes_cookbooks_attribute_file_ordering.rst

**Comment by vinyar** [comment]
also here - https://github.com/chef-cookbooks/compat_resource/blob/master/files/lib/chef_compat/monkeypatches/chef/run_context.rb

**Comment by brewn** [comment]
`include_attribute` is replaced by `metadata.rb` in both Chef 12 and Chef 13 (and Chef 11, as the note in that guide indicates), which are the two versions currently supported: https://docs.chef.io/platforms.html#versions-and-status

The boneyard is definitely the right place for this.
