### ISSUE TITLE
Add breadcrumb links to the top of docs pages

### ISSUE THREAD

**Issue by mivok** [chef/chef-web-docs#589]
For example, if you click on https://docs.chef.io/deprecations_custom_resource_cleanups.html it shows you a deprecation page for chef. However, there's no obvious place to click to find the list of other deprecations. It would be nice to have at the top of the page some breadcrumb links to show you where you are in the site and to get to the parents/grandparents of pages.

For example, the parent of the deprecation page appears to be https://docs.chef.io/chef_deprecations_client.html which is under Chef and Getting Started in the navigation menu to the left, so it would be nice to have the top have something that looks like:

> Chef > Getting Started > Deprecations > Custom Resource Cleanups 

with links to any of the sections that are in fact pages themselves.

**Comment by brewn** [comment]
This has been suggested as part of the upcoming redesign work. Closing this for now.
