### ISSUE TITLE
Clarify what resources can be used with dsc_resource

### ISSUE THREAD

**Issue by usepowershell** [chef/chef-web-docs#59]
chef-web-docs/includes_resources/includes_resource_dsc_resource_requirements.rst  Should include a note that dsc_resource can only use binary or script resources.  Composite DSC resources are not supported by dsc_resource.  See - https://discourse.chef.io/t/dsc-resource-will-not-work-with-composite-resources/8443/2?u=steven_murawski

**Comment by davidwrede** [comment]
These updates are in the live docs.
