### ISSUE TITLE
Rework the chef client upgrade docs

### ISSUE THREAD

**Issue by tas50** [chef/chef-web-docs#617]
We have a doc for upgrading from earlier Chef clients to Chef 12, but we lack anything in upgrading to Chef 12. This doc needs to be folded into the deprecation page probably and should just reference the process of referencing that doc, running foodcritic, and deploying the new version to a single node. As it stands right now some of the steps aren't the most helpful and without Chef 13 this doc is pretty dated.

**Comment by kagarmoe** [comment]
Solved by recent changes. Closed by https://github.com/chef/chef-web-docs/pull/3660
