### ISSUE TITLE
Analytics install instructions have a 'broken' step

### ISSUE THREAD

**Issue by vinyar** [chef/chef-web-docs#62]
Doc url: https://docs.chef.io/install_analytics.html

Issue: Below step only works in combined mode and presently explodes, leading users to believe something's gone wrong with their Analytics install. There is a pending code fix, however until it's done, best remove it from the doc to avoid extra confusion.

```
Verify the installation on the Chef Analytics server:
$ opscode-analytics-ctl test
```

Internal Refs:
https://getchef.zendesk.com/agent/tickets/9620
https://chefio.atlassian.net/browse/TRI-156

**Comment by davidwrede** [comment]
Attached commit addressed issue, so I'm going to close the issue.
