### ISSUE TITLE
Missing steps for user add...

### ISSUE THREAD

**Issue by larryebaum** [chef/chef-web-docs#63]
URL: https://docs.chef.io/install_delivery_aws.html

Beneath the Configure Delivery section is the subsection for Add Users (below). It states, "...use the follow procedure to create a new user...", however, that procedure is not included.

Add Users¶
The default admin account should not be used after Delivery is installed. Instead, use the following procedure to create a new user for yourself, then log out as admin and log back in as the user you created.

**Comment by davidwrede** [comment]
This topic has been removed because the installation procedure for Chef Automate (i.e. Delivery) has changed.
