### ISSUE TITLE
404 Link in Test Kitchen Docs

### ISSUE THREAD

**Issue by isuftin** [chef/chef-web-docs#64]
https://github.com/chef/chef-web-docs/blob/1100a23441e773656e0168e638450355b513613a/includes_test_kitchen/includes_test_kitchen_yml_example_mysql.rst#L7

https://github.com/chef-cookbooks/mysql/blob/master/.kitchen.cloud.yml is not a thing

**Comment by davidwrede** [comment]
Hi Ivan,

Thanks for the note. The updated topic should be live later today.

Thanks,
Dave

**Comment by davidwrede** [comment]
Hey @isuftin, not sure how this feel off my plate, but I've got a fix in now to remove the broken link.

Thanks,
Dave
