### ISSUE TITLE
Add an example of using LAZY and Execute to the docs.

### ISSUE THREAD

**Issue by vinyar** [chef/chef-web-docs#641]
Would be great to add an example of using `execute` with `lazy` to the docs.

Origin where I found this gold:
https://github.com/chef-cookbooks/habitat-build/blob/157f6fd662dba18f4f80312a40426e1c441ab4a9/resources/hab_build.rb#L83-L88

```
action :publish do
  execute 'upload-pkg' do
    command(lazy do
      url_opt = "--url #{depot_url}" if depot_url
...
```

**Comment by lamont-granquist** [comment]
Offhand I can see why that cookbook needs to do that.  The action gets its own compile-converge mode and there's nothing that I can see happening during compile time that would require lazying any of those values to converge time.

This smells like it was copypasta'd from someplace that was doing horrible things -- probably incorrect things -- and lazy'ing here is unnecessary.  And the 99.9% use case is nobody should need to do this, and its probably signifying that the execute resource needs to be moved into a custom resource or that the `depot_url` variable needs to be fully constructed at compile time before this resource is called.

Pretty certain this shouldn't get documented as something people should actually do -- and the cookbook really needs a PR to either remove that, or to clearly document why that trick is deemed necessary.

**Comment by kagarmoe** [comment]
Documented in the [LazyInResourceGuard](https://docs.chef.io/workstation/cookstyle/chef_correctness_lazyinresourceguard/).
