### ISSUE TITLE
edit_resource and other resource manipulation DSL elements are missing

### ISSUE THREAD

**Issue by juliandunn** [chef/chef-web-docs#646]
I noticed that `edit_resource` and friends are missing from our documentation. These DSL elements were added a year ago: https://github.com/chef/chef/commit/544a9127cf3ed738d642b2490ed3063f1623c36c

In tackling this ticket, we should also be removing any references to chef-rewind.

**Comment by kagarmoe** [comment]
Thanks! I think that the resources you're looking for are on https://docs.chef.io/dsl_recipe.html.

**Comment by ehaselwanter** [comment]
can we add an example for edit_resource with the behaviour of 

> In Chef 13, resources with the same name will be treated as entirely separate, without any cloning of properties.

which one will I change with `edit_resource` ? referring to the _entirely separate_
