### ISSUE TITLE
Delivery CLI Install for Windows doc is wrong

### ISSUE THREAD

**Issue by usepowershell** [chef/chef-web-docs#66]
Currently we have 

```
. { iwr -useb https://omnitruck.chef.io/install.ps1 } | iex; install
```

This will install Chef Client.

For Delivery CLI we can use

```
. { iwr -useb https://omnitruck.chef.io/install.ps1 } | iex; install -project delivery-cli -architecture x86_64
```

**Comment by davidwrede** [comment]
Since the Delivery CLI is part of the DK install, we no longer have the older instructions available (hence, no need to update them).
