### ISSUE TITLE
Chef components diagram needs to be updated

### ISSUE THREAD

**Issue by tas50** [chef/chef-web-docs#666]
The diagram at https://docs.chef.io/_images/chef_overview.svg needs to be updated.

Kitchen should be Test Kitchen
Rubocop should be Cookstyle
Foodcritic should be next to Cookstyle

**Comment by kagarmoe** [comment]
I've sent a issue to graphic design.

**Comment by kagarmoe** [comment]
Thanks. Closed by PR #699.
