### ISSUE TITLE
Chef overview graphics plural vs. singular

### ISSUE THREAD

**Issue by tas50** [chef/chef-web-docs#669]
In the components section of https://docs.chef.io/chef_overview.html we have graphics for each of the cookbook components. They're all plural except for "template", which should be "templates". 

![screen shot 2017-05-17 at 10 20 22 am](https://cloud.githubusercontent.com/assets/1015200/26167040/79b37cde-3aea-11e7-848d-04aba5a5fbdf.png)

**Comment by kagarmoe** [comment]
I've sent a issue to graphic design.

**Comment by kagarmoe** [comment]
Thanks! Fixed by #699.
