### ISSUE TITLE
Stray ".rst" in Properties section of chocolatey_package docs

### ISSUE THREAD

**Issue by itmustbejj** [chef/chef-web-docs#71]
![screen shot 2016-06-08 at 2 45 33 pm](https://cloud.githubusercontent.com/assets/382062/15910371/c4130e0a-2d87-11e6-90b7-0571054218c1.png)

https://docs.chef.io/resource_chocolatey_package.html

**Comment by davidwrede** [comment]
Fixed in latest docs.
