### ISSUE TITLE
Google indexed page https://docs.chef.io/containers.html throws a 403

### ISSUE THREAD

**Issue by gramosbr** [chef/chef-web-docs#82]
https://docs.chef.io/search.html?q=containers
https://www.chef.io/solutions/containers/

**Comment by ghostsquad** [comment]
👍  I came from this page: https://www.chef.io/solutions/containers/ to find the link at the bottom of the page to https://docs.chef.io/containers.html to not exist.

**Comment by davidwrede** [comment]
Hi @gramosbr and @ghostsquad, our replacement for the containers topic is now a redirect to the [Habitat site](https://www.habitat.sh). Habitat is a technology that we created to package up an application and any automation for it into one artifact. This artifact can be then exported to a Docker image and run inside a container, if you wish.
