### ISSUE TITLE
Azure linux chef extension doesn't support SuSE

### ISSUE THREAD

**Issue by akhileshkumar02** [chef/chef-web-docs#820]
Linux distributor has no entry for SuSE in shared.sh, so chef packages are not getting installed. 

get_linux_distributor(){
#### Using python -mplatform command to get distributor name #####
  if python -mplatform | grep centos > /dev/null; then
    linux_distributor='centos'
  elif python -mplatform | grep Ubuntu > /dev/null; then
    linux_distributor='ubuntu'
  elif python -mplatform | grep debian > /dev/null; then
    linux_distributor='debian'
  elif python -mplatform | grep redhat > /dev/null; then
    linux_distributor='rhel'
  fi
  echo "${linux_distributor}"
}

**Comment by brewn** [comment]
I'd suggest opening an issue against the extension itself, to request the inclusion of SuSe support. 

https://github.com/chef-partners/azure-chef-extension
