### ISSUE TITLE
All docs for pre-Automate stuffs are gone

### ISSUE THREAD

**Issue by coderanger** [chef/chef-web-docs#83]
https://github.com/chef/chef-web-docs/commit/23a40d79213008e92c08c7eff7ddcf26ed7f9361 made lots of things in to redirects inappropriately. People are still using those products even if new ones are available so the docs should still be there.

**Comment by davidwrede** [comment]
Noah,

Sorry about the redirects and missing docs. We're getting those added back in today. 

Thanks,
Dave

**Comment by davidwrede** [comment]
Content supporting products like Analytics was added back into the doc set soon after my response, so I'm closing out this issue.
