### ISSUE TITLE
Chef Server API docs url for client keys is incorrect

### ISSUE THREAD

**Issue by Tech356** [chef/chef-web-docs#86]
The documentation for the `clients/client/keys` incorrectly uses `client/client/keys` as the url. 

Searching for "client/" on the Chef Server API page will show all the incorrect instances. 

https://docs.chef.io/api_chef_server.html

In addition, the raml-docs in the chef-server repo are incorrect. Lines 17 and 20 in the keys.yaml file:

https://github.com/chef/chef-server/blob/bb28b489960c8fae6ac061bf2dab5800142b22a3/src/oc_erchef/raml-docs/organizations/clients/keys.yaml

**Comment by kagarmoe** [comment]
Thanks for your contribution!
