### ISSUE TITLE
Unused admin parameter still listed on the Chef Server API page

### ISSUE THREAD

**Issue by Tech356** [chef/chef-web-docs#87]
The Chef Server API docs has the `admin` parameter listed as a usable parameter on the `/clients` POST and `/clients/NAME` PUT endpoints. 

https://docs.chef.io/api_chef_server.html

The Release Notes for Chef Server 12.1.0 say that:

```
In client creation and update, the last remnants of the admin flag have been 
removed. It was previously partially supported in that we would capture and 
update the value, but the value was unused in the system. If submitted in 
POST/PUT of a client or user, it is ignored.
```

https://github.com/chef/chef-server/blob/master/PRIOR_RELEASE_NOTES.md#api-changes-and-additions-2

**Comment by kagarmoe** [comment]
Thanks for your contribution!
