### ISSUE TITLE
Chef Server API docs show the use of the removed private_key parameter

### ISSUE THREAD

**Issue by Tech356** [chef/chef-web-docs#88]
The Chef Server API docs page shows the use of the `private_key` parameter in the `/clients/NAME` and `/users/NAME` PUT endpoints. The use of the `private_key` parameter has been removed and will throw a HTTP 400 error when used. 

https://docs.chef.io/api_chef_server.html

From the Release Notes:

```
Including any of public_key, private_key, or create_key in PUT requests to 
client/users will cause a 400 response with detailed message.
```

https://github.com/chef/chef-server/blob/master/PRIOR_RELEASE_NOTES.md#api-changes-and-additions-2

**Comment by kagarmoe** [comment]
Thanks for your contribution!
