### ISSUE TITLE
Broken template include on resource_dsc_resource.html

### ISSUE THREAD

**Issue by itmustbejj** [chef/chef-web-docs#89]
https://docs.chef.io/resource_dsc_resource.html

<img width="778" alt="screen shot 2016-07-18 at 10 16 04 am" src="https://cloud.githubusercontent.com/assets/382062/16921901/bb0d555a-4cd0-11e6-9735-6373a831f105.png">

**Comment by jamescott** [comment]
Thank you! This fix is building now.
