### ISSUE TITLE
Bootstrap templates commands lo longer correct

### ISSUE THREAD

**Issue by spuder** [chef/chef-web-docs#938]
The docs on bootstrap templates have commands that no longer work

https://docs.chef.io/knife_bootstrap.html#ubuntu-14-04

>The following example shows how to modify the default script for Ubuntu 14.04. First, copy the bootstrap template from the default location. If the chef-client is installed from a RubyGems, the full path can be found in the gem contents. For example:
```
$ gem contents chef | grep ubuntu14.04-gems
/Users/grantmc/.rvm/gems/ruby-2.0/gems/chef-12.0.2/lib/chef/knife/bootstrap/ubuntu14.04-gems.erb
```

There is no ubuntu14.04-gems listed. 
I suspect everything has been combined under chef-full

    gem contents chef | grep template | grep erb

**Comment by brewn** [comment]
Yeah, this definitely needs some updating. In the meantime, this covers creating your own bootstrap template from `chef-full`: https://docs.chef.io/install_chef_air_gap.html#create-a-bootstrap-template

**Comment by brewn** [comment]
#999
