### ISSUE TITLE
Mention the word twiddle-wakka in the documentation on versions

### ISSUE THREAD

**Issue by aaronblythe** [chef/chef-web-docs#94]
I have had the opportunity to teach and discuss Chef to many new users over the past few years.  A concept that is hard for users that are not yet accustomed to ruby is the `~>`.  More over this is a tough set of characters to google search.  By using the term `twiddle-wakka` you give the user something to sync google's teeth into.

While the documentation at https://docs.chef.io/config_rb_metadata.html is currently likely enough to explain:

```
A range of chef-client versions that are supported by this cookbook.

For example, to match any 12.x version of the chef-client, but not 11.x or 13.x:
chef_version "~> 12"
```

Providing the word to google and find out more and a link to http://guides.rubygems.org/patterns/#declaring-dependencies will likely give the more curious an avenue to learn more and understand the history.

**Comment by davidwrede** [comment]
Hi @aaronblythe, thanks for the suggestion and we have updated the docs to mention twiddle-wakka. 

See PR #386.
