### ISSUE TITLE
Knife search by IP documentation is hard to understand

### ISSUE THREAD

**Issue by martinmosegaard** [chef/chef-web-docs#954]
I had a hard time learning how to find a Chef node by its IP address. Usecase was that I had the IP of a machine and wanted to see if it was managed by Chef (I could also look at `c:\chef\client.rb` on the machine, but this was for a list of VMs).

On this page:
https://docs.chef.io/knife_search.html 

It says:
```
To find all IP address that are on the same network, enter the following:
$ knife search node 'network_interfaces__addresses:192.168*'
where 192.168* is the network address for which the search will be run.
```

That syntax with using underscores did not work for me. I figured out I could use `knife node show name:somenodeiknow -F json` to see the fields that could be queried. One of these were `ipaddress`. 

So I think this is a better example or finding a machine by IP address which we could add to the docs:

```
knife search node 'ipaddress:10.20.123.*'
```
(to find all in the `10.20.123` subnet)

**Comment by brewn** [comment]
Closed, thanks to @jmassardo
