### ISSUE TITLE
No docs for 12.11 or 12.12

### ISSUE THREAD

**Issue by coderanger** [chef/chef-web-docs#96]
or, more important, no release notes. Would be good to sync, though we should probably sort out how we ended up so far behind.

**Comment by davidwrede** [comment]
@coderanger, we're a bit resource constrained right now and I've been working through other doc backlog issues, but the 12.11 docs should go out later today.

I'll start on the 12.12 docs after that.

**Comment by davidwrede** [comment]
12.12 and 12.13 docs are out now.
