### ISSUE TITLE
Dash chef docs

### ISSUE THREAD

**Issue by jjasghar** [chef/chef-web-docs#984]
From the chef summit sea we would like to know the process and who owns the chef docs in dash. 

We would like to extend it to habitat and inspec. 

/cc @maritinisoft

**Comment by brewn** [comment]
The Chef docs in Dash appear to be pulled right from our existing doc site. They contain some fairly recent updates of ours, though they're not 100% current from what I can tell. I'm going to look into whether or not anyone in the organization updating them, or if it's something we should take over ourselves. 

Also, I'm going to reach out to them re: Habitat and InSpec. Thanks for the suggestion @jjasghar @martinisoft
